import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {Vec2} from 'planck';
import {Simulation} from '../src/simulation/world';import {arena,spawnPoint} from '../src/simulation/arena';import {ARENAS} from '../src/simulation/arenas';import {setSimulationArena,simulationArena} from '../src/simulation/arena-adapter';import {sizeSimulation} from '../src/simulation/roster';import {capture,restore} from '../src/simulation/state';
test('M8 arena adapters preserve every other byte of approved networking and presentation',()=>{
 const b=JSON.parse(readFileSync(new URL('../docs/milestone-8-adapter-preservation.json',import.meta.url),'utf8'));
 for(const [path,record]of Object.entries(b.files)as [string,{sha256:string;changes:{from:string;to:string}[]}][]){let s=readFileSync(new URL(`../${path}`,import.meta.url),'utf8');for(const c of record.changes){assert.ok(s.includes(c.from),path);s=s.replace(c.from,c.to);}assert.equal(createHash('sha256').update(s).digest('hex'),record.sha256,path);}
});
test('original arena is exact and both arenas have safe non-overlapping 2–8 floor spawns',()=>{
 assert.strictEqual(ARENAS.canopy.solids,arena);assert.deepEqual(ARENAS.swingworks.solids.slice(0,4),arena.slice(0,4));
 for(const id of ['canopy','swingworks']as const)for(let count=2;count<=8;count++){const sim=new Simulation();setSimulationArena(sim,id);sizeSimulation(sim,count);sim.reset();for(let i=0;i<count;i++){const p=spawnPoint(i,count);assert.equal(sim.frogs[i].body.getPosition().x,p.x);for(const r of ARENAS[id].solids){const x=Math.max(r.x-r.w/2,Math.min(p.x,r.x+r.w/2)),y=Math.max(r.y-r.h/2,Math.min(p.y,r.y+r.h/2));assert.ok(Math.hypot(p.x-x,p.y-y)>sim.tuning.frogRadius,'spawn inside terrain');}}}
});
test('geometry switches preserve dynamic bodies and tuning, clear ropes and serialize matching terrain anchors',()=>{
 const a=new Simulation(),body=a.frogs[0].body,tuning={...a.tuning};setSimulationArena(a,'swingworks');assert.equal(a.frogs[0].body,body);assert.deepEqual(a.tuning,tuning);sizeSimulation(a,8);a.reset();const f=a.frogs[0];f.body.setTransform(Vec2(14,11),0);a.setInput(0,{x:0,y:-1,held:true});for(let i=0;i<35;i++)a.step();assert.equal(f.tongue?.phase,'attached');assert.ok(f.tongue?.target&&!f.tongue.target.isDynamic());const state=capture(a),b=new Simulation();setSimulationArena(b,'swingworks');restore(b,state);assert.deepEqual(capture(b),state);const v=f.body.getLinearVelocity().clone();a.detach(f);assert.deepEqual(f.body.getLinearVelocity(),v);setSimulationArena(a,'canopy');assert.equal(simulationArena(a),'canopy');assert.ok(a.frogs.every(f=>!f.tongue));let n=0;for(let b=a.world.getBodyList();b;b=b.getNext())if(!b.isDynamic())n++;assert.equal(n,arena.length);
});
test('side-tier rises fit the approved full charged-jump ballistic height without retuning',()=>{const s=new Simulation();const height=s.tuning.chargedJumpImpulse**2/(2*s.tuning.gravity);assert.ok(height>4.5+s.tuning.frogRadius);assert.equal(s.tuning.chargedJumpImpulse,18);assert.equal(s.tuning.chargeHorizontalImpulse,2);});
