import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {Vec2,Box,Circle} from 'planck';
import {MODIFIERS,CHAOS_TUNING,applyChaos,effectiveTuning,eligibleModifierIds,validModifiers,type ModifierId} from '../src/chaos/registry';
import {ChaosVoting} from '../src/chaos/voting';import {Simulation} from '../src/simulation/world';import {defaults,DT} from '../src/simulation/config';import {capture,restore} from '../src/simulation/state';import {sizeSimulation} from '../src/simulation/roster';import {setSimulationArena} from '../src/simulation/arena-adapter';import {arenaList} from '../src/simulation/arenas';import {assistedDirection} from '../src/simulation/aim-assist';import {syncFrozenBodies,stepFrozenBodies} from '../src/game/frozen-bodies';import {POISON_BALANCE} from '../src/game/poison-balance';import {frogBodyContacts} from '../server/outbreak-room';import {OutbreakRules,OUTBREAK} from '../src/game/outbreak';import {FreezeRules,FREEZE} from '../src/game/freeze-tag';import {ClassicRules,CLASSIC} from '../src/game/classic-tag';import {chaosBPreservedSource,chaosBRefinementPreservedSource} from './preserved-source';
const B:ModifierId[]=['turbo_toads','tiny_trouble','mega_frogs','super_suckers','magnet_mouths'];
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
function fresh(arena=arenaList[0].id,count=2){const s=new Simulation();setSimulationArena(s,arena);sizeSimulation(s,count);s.reset();return s;}
function pair(s:Simulation,distance:number){s.frogs[0].body.setTransform(Vec2(18,19),0);s.frogs[1].body.setTransform(Vec2(18+distance,19),0);s.world.step(0);return frogBodyContacts(s);}
test('B numerical values, stable composition, invalid/duplicate/conflict sanitization and complete expiry',()=>{
 const turbo=effectiveTuning(['turbo_toads']);close(turbo.groundSpeed,9);close(turbo.groundAcceleration,96);assert.equal(turbo.airAcceleration,10);assert.equal(turbo.grappleTakeupSpeed,4);
 const superPull=effectiveTuning(['super_suckers']);close(superPull.grapplePullAcceleration,57.6);close(superPull.grappleTakeupSpeed,4.4);assert.equal(superPull.grappleMaxPullSpeed,8);
 assert.deepEqual(validModifiers(['unknown','mega_frogs','tiny_trouble','tiny_trouble']),['tiny_trouble']);
 for(const id of B){const s=fresh();for(let k=0;k<10;k++){applyChaos(s,[id]);applyChaos(s,[]);}assert.deepEqual(s.tuning,defaults);assert.equal(s.chaosAimDegrees,8);assert.equal(s.chaosSuperSuckers,false);for(const f of s.frogs){close((f.body.getFixtureList()!.getShape()as Circle).getRadius(),.45);close(f.body.getMass(),1);}}
 for(const a of MODIFIERS)for(const b of MODIFIERS)for(const c of MODIFIERS){const ids=[a.id,b.id,c.id];assert.deepEqual(effectiveTuning(ids),effectiveTuning([...ids].reverse()));const t=effectiveTuning(ids);assert.ok(t.groundSpeed<=9+1e-9);assert.equal(t.grappleMaxPullSpeed,8);assert.equal(t.frogMass,1);assert.equal(t.jumpImpulse,9.5);}
});
test('Tiny/Mega real fixtures, constant mass/momentum/body identity, authoritative state and frozen rescue restoration',()=>{
 for(const id of ['tiny_trouble','mega_frogs']as const){const s=fresh(),body=s.frogs[0].body;body.setLinearVelocity(Vec2(3,-4));applyChaos(s,[id]);const radius=id==='tiny_trouble'?.3375:.5625;close((body.getFixtureList()!.getShape()as Circle).getRadius(),radius);close(body.getMass(),1);assert.equal(s.frogs[0].body,body);assert.deepEqual(body.getLinearVelocity(),Vec2(3,-4));const snap=capture(s),p=fresh();applyChaos(p,[id]);restore(p,snap);assert.deepEqual(capture(p),snap);
  syncFrozenBodies(s,[true,false]);applyChaos(s,[]);syncFrozenBodies(s);close(body.getMass(),1);close((body.getFixtureList()!.getShape()as Circle).getRadius(),.45);assert.ok(body.isDynamic());
 }
});
test('all four arenas: safe 2–8 spawns, bounded deterministic trajectories, recovery and baseline restoration',()=>{
 for(const arena of arenaList)for(const count of [2,8])for(const id of B){const a=fresh(arena.id,count),b=fresh(arena.id,count);for(const s of[a,b]){applyChaos(s,[id]);s.reset();s.world.step(0);for(const f of s.frogs){const p=f.body.getPosition();assert.ok(p.x>s.tuning.frogRadius&&p.x<40-s.tuning.frogRadius);assert.ok(p.y+s.tuning.frogRadius<21.5);for(let edge=f.body.getContactList();edge;edge=edge.next)assert.equal(edge.contact.isTouching(),false,`${arena.id}/${id} spawn overlap`);}}
  for(let tick=0;tick<240;tick++){for(const s of[a,b]){s.frogs.forEach((_,i)=>s.setInput(i,{x:(tick+i)%100<50?1:-1,y:-1,held:(tick+i*7)%90<35}));s.step();}assert.deepEqual(capture(a),capture(b));}
  for(const f of a.frogs){assert.ok(Number.isFinite(f.body.getPosition().x));assert.ok(f.body.getLinearVelocity().length()<100);}
  a.frogs[0].body.setTransform(Vec2(-9,30),0);a.step();assert.ok(a.frogs[0].body.getPosition().x>0);applyChaos(a,[]);a.reset();assert.deepEqual(a.tuning,defaults);
 }
});
test('actual adjusted body contacts drive Poison, Freeze and Classic; tongues alone do not tag',()=>{
 for(const id of['tiny_trouble','mega_frogs']as const){const s=fresh();applyChaos(s,[id]);const r=s.tuning.frogRadius;assert.equal(pair(s,2*r+.04).length,0);assert.ok(pair(s,2*r-.015).length>0);const contacts=frogBodyContacts(s);
  const modes=[new OutbreakRules([0,1],0,{...OUTBREAK,announcementTicks:1,countdownTicks:1}),new FreezeRules([0,1],0,{...FREEZE,announcementTicks:1,countdownTicks:1}),new ClassicRules([0,1],0,{...CLASSIC,announcementTicks:1,countdownTicks:1})];for(const mode of modes){mode.advanceClock(2);assert.deepEqual(mode.infect(3,[]),[]);assert.deepEqual(mode.infect(4,contacts),[1]);}
  s.frogs[0].body.setLinearVelocity(Vec2(20,20));s.setInput(0,{x:1,y:-1,held:true});stepFrozenBodies(s,[true,false],()=>s.step());assert.deepEqual(s.frogs[0].body.getLinearVelocity(),Vec2(0,0));assert.equal(s.frogs[0].tongue,undefined);
 }
});
test('Super Suckers applies reciprocal role-relative pull, bounded closing speed and momentum-preserving release',()=>{
 for(const poisoned of[false,true]){const speeds:number[]=[];for(const active of[false,true]){const s=fresh();if(active)applyChaos(s,['super_suckers']);const f=s.frogs[0],target=s.frogs[1].body;f.body.setTransform(Vec2(4,7),0);target.setTransform(Vec2(10,7),0);if(poisoned)f.poisonPullFromTick=0;
  f.tongue={phase:'attached',direction:{x:1,y:0},tip:{x:10,y:7},distance:6,length:6,target,localAnchor:{x:0,y:0},joint:{setMaxLength(){}}as any};s.pullGrapple(f);const va=f.body.getLinearVelocity().x,vb=target.getLinearVelocity().x;close(va,-vb);speeds.push(va);close(va*2,48*(active?1.2:1)*(poisoned?POISON_BALANCE.grapplePullMultiplier:1)*DT);
  f.body.setLinearVelocity(Vec2(10,2));target.setLinearVelocity(Vec2(0,2));s.pullGrapple(f);assert.equal(f.body.getLinearVelocity().x,10);f.tongue!.joint=undefined;const v=f.body.getLinearVelocity().clone();s.detach(f);assert.deepEqual(f.body.getLinearVelocity(),v);
 }close(speeds[1]/speeds[0],1.2);}
});
test('Magnet: 6 degree cone, range, terrain occlusion, frozen exclusion, deterministic target, committed flight',()=>{
 const s=fresh();const f=s.frogs[0],target=s.frogs[1];f.body.setTransform(Vec2(5,20),0);const position=(deg:number,d=5)=>target.body.setTransform(Vec2(5+Math.cos(deg*Math.PI/180)*d,20+Math.sin(deg*Math.PI/180)*d),0);
 position(5);assert.equal(assistedDirection(s,f,{x:1,y:0},6).target,1);position(6.1);assert.equal(assistedDirection(s,f,{x:1,y:0},6).target,undefined);position(3,13);assert.equal(assistedDirection(s,f,{x:1,y:0},6).target,undefined);position(3);const wall=s.world.createBody(Vec2(7,20));wall.createFixture(Box(.1,1));assert.equal(assistedDirection(s,f,{x:1,y:0},6).target,undefined);s.world.destroyBody(wall);syncFrozenBodies(s,[false,true]);assert.equal(assistedDirection(s,f,{x:1,y:0},6).target,undefined);syncFrozenBodies(s);applyChaos(s,['magnet_mouths']);position(5);s.fire(f,{x:1,y:0,held:true});assert.equal(f.aimAssistTarget,1);const dir={...f.tongue!.direction};position(-5);s.updateTongue(f);assert.deepEqual(f.tongue!.direction,dir);assert.equal(s.tuning.tongueRange,12);
 const a=fresh();sizeSimulation(a,4);a.frogs[0].body.setTransform(Vec2(5,20),0);a.frogs[1].body.setTransform(Vec2(10,20.1),0);a.frogs[2].body.setTransform(Vec2(10,20.1),0);a.frogs[3].body.setTransform(Vec2(12,20.1),0);assert.equal(assistedDirection(a,a.frogs[0],{x:1,y:0},6).target,3);a.frogs[3].body.setTransform(Vec2(12,22),0);assert.equal(assistedDirection(a,a.frogs[0],{x:1,y:0},6).target,1);
});
test('compatibility, three distinct families, guaranteed renewal, maximum-three conveyor and rematch reset',()=>{
 for(const arena of arenaList)for(const mode of['poison','freeze','classic']as const){assert.equal(eligibleModifierIds(['tiny_trouble'],mode,arena.id).includes('mega_frogs'),false);assert.equal(eligibleModifierIds(['mega_frogs'],mode,arena.id).includes('tiny_trouble'),false);const c=new ChaosVoting(true,()=>.43);for(let round=0;round<30;round++){const prior=[...c.active];assert.ok(c.open(round*20000,mode,arena.id));assert.equal(c.choices.length,3);assert.equal(new Set(c.choices).size,3);if(prior.length===3)assert.ok(c.choices.includes(prior[0]));const eligible=eligibleModifierIds(prior,mode,arena.id);assert.ok(c.choices.every(id=>eligible.includes(id)));c.advance(round*20000+15000,[]);assert.equal(c.active.length,Math.min(3,prior.length+1));assert.deepEqual(validModifiers(c.active).sort(),[...c.active].sort());c.advance(round*20000+16500,[]);}c.reset();assert.deepEqual(c.active,[]);}
});
test('approved A source and protected iPhone/input/modes/arenas/audio remain exact',()=>{const m=JSON.parse(readFileSync(new URL('../docs/chaos-b-preservation.json',import.meta.url),'utf8'));const hash=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');for(const[p,r]of Object.entries(m.files)as[string,any][]){assert.equal(hash(chaosBPreservedSource(p)),r.beforeSha256,p);assert.equal(hash(chaosBRefinementPreservedSource(p)),r.afterSha256,p);}for(const[p,h]of Object.entries(m.protected))assert.equal(hash(readFileSync(new URL('../'+p,import.meta.url))),h,p);});
