import {test} from 'node:test';import assert from 'node:assert/strict';
import {ClassicRules,CLASSIC} from '../src/game/classic-tag';import {Moments} from '../src/presentation/moments';import {MODES,isGameMode} from '../src/game/modes';
const timing={...CLASSIC,announcementTicks:1,countdownTicks:1};const start=(n=3)=>{const r=new ClassicRules(Array.from({length:n},(_,i)=>i),0,timing);r.advanceClock(2);return r;};
test('Classic is third mode; existing defaults retained; invalid mode rejected',()=>{assert.deepEqual(MODES.map(m=>m.id),['poison','freeze','classic']);assert.ok(isGameMode('classic'));assert.ok(!isGameMode('unknown'));});
test('body transfer once per tick, nearest centre then roster tie independent callback order',()=>{for(const pairs of [[[0,1],[0,2]],[[0,2],[0,1]]]as[number,number][][]){const r=start();assert.deepEqual(r.infect(3,pairs,[{x:0,y:0},{x:2,y:0},{x:1,y:0}]),[2]);assert.equal(r.it,2);assert.equal(r.transfers,1);assert.deepEqual(r.infect(3,[[2,1]]),[]);const tie=start();tie.infect(3,pairs,[{x:0,y:0},{x:-1,y:0},{x:1,y:0}]);assert.equal(tie.it,1);}});
test('tongue or unrelated contacts cannot tag; new IT one-second protection; continued contact transfers on expiry',()=>{const r=start();r.infect(3,[]);r.infect(3,[[1,2]]);assert.equal(r.it,0);r.infect(4,[[0,1]]);assert.equal(r.it,1);r.infect(63,[[0,1]]);assert.equal(r.it,1);r.infect(64,[[0,1]]);assert.equal(r.it,0);assert.equal(r.protectedUntil,124);});
test('fixed 60-second scoring excludes IT, includes protection, deadline prevents tag and is idempotent',()=>{const r=start(2);r.infect(1802,[[0,1]]);assert.deepEqual(r.records.map(p=>p.activeTicks),[0,1800]);r.infect(3602,[[0,1]]);assert.equal(r.phase,'round-results');assert.equal(r.it,1);assert.deepEqual(r.records.map(p=>p.activeTicks),[1800,1800]);assert.deepEqual(r.roundWinners,[0,1]);assert.deepEqual(r.totals,[30,30]);r.infect(5000,[[0,1]]);assert.deepEqual(r.totals,[30,30]);assert.equal(r.view(5000).elapsedMs,60000);assert.deepEqual(r.view(5000).classic!.itMs,[30000,30000]);});
test('every 2–8 player starts IT exactly once; shared round and final ties and host-led transitions',()=>{for(let count=2;count<=8;count++){const order=Array.from({length:count},(_,i)=>count-i-1),r=new ClassicRules(order,0,timing);let tick=0;const seen=[];for(let round=0;round<count;round++){assert.equal(r.patientZero,order[round]);assert.equal(r.it,order[round]);assert.equal(r.next(tick),false);seen.push(r.it);r.advanceClock(tick+2);r.infect(tick+3602,[]);assert.equal(r.roundWinners.length,count-1);assert.ok(r.records.every(p=>p.infectiousTick===null));r.next(tick+3602);tick+=3602;}assert.equal(r.phase,'match-results');assert.equal(new Set(seen).size,count);assert.equal(r.view(tick).matchWinners.length,count);assert.ok(r.totals.every(n=>n===60*(count-1)));}});
test('Classic local tag notification only on authoritative role change, no poison/last-safe events',()=>{const r=start(),m=new Moments();assert.ok(m.update(r.view(2),1).some(e=>e.text==='CLASSIC TAG!'));r.infect(3,[[0,1]]);assert.ok(m.update(r.view(3),1).some(e=>e.text==='YOU’RE IT!'));assert.deepEqual(m.update(r.view(4),1),[]);r.infect(63,[[1,2]]);assert.ok(m.update(r.view(63),1).some(e=>e.cue==='infect'&&!e.text));});

test('Classic tongue attachment alone never tags; real body contacts do across all arenas',async()=>{const {Simulation}=await import('../src/simulation/world');const {sizeSimulation}=await import('../src/simulation/roster');const {setSimulationArena}=await import('../src/simulation/arena-adapter');const {arenaList}=await import('../src/simulation/arenas');const {frogBodyContacts}=await import('../server/outbreak-room');const {Vec2}=await import('planck');for(const arena of arenaList){const s=new Simulation();sizeSimulation(s,2);setSimulationArena(s,arena.id);s.frogs[0].body.setTransform(Vec2(12,9),0);s.frogs[1].body.setTransform(Vec2(14,9),0);s.setInput(0,{x:1,y:0,held:true});const r=start(2);let attached=false;for(let n=0;n<12;n++){s.step();const t=s.frogs[0].tongue;attached||=!!t?.target&&t.target===s.frogs[1].body;r.infect(3+n,frogBodyContacts(s),s.frogs.map(f=>f.body.getPosition()));}assert.ok(attached,arena.id);assert.equal(r.it,0,arena.id);s.clearInputs();s.frogs[0].body.setTransform(Vec2(20,21.05),0);s.frogs[1].body.setTransform(Vec2(20.87,21.05),0);s.world.step(1/60);r.infect(20,frogBodyContacts(s),s.frogs.map(f=>f.body.getPosition()));assert.equal(r.it,1,arena.id);}});
