import {multitouchPreservedSource,recoveryPreservedSource} from './preserved-source';
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {Moments} from '../src/presentation/moments';import {SOUNDS} from '../src/presentation/audio';import {OutbreakRules} from '../src/game/outbreak';
test('M9 preserves physical input, viewport/canvas code and all approved authority/physics/arenas outside exact presentation adapters',()=>{const m=JSON.parse(readFileSync(new URL('../docs/milestone-9-preservation.json',import.meta.url),'utf8'));const hash=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');for(const[path,expected]of Object.entries(m.protected))assert.equal(hash(multitouchPreservedSource(path)),expected,path);for(const[path,r]of Object.entries(m.files)as[string,{sha256:string;changes:{from:string;to:string}[]}][]){let s=recoveryPreservedSource(path);for(const c of r.changes){assert.ok(c.from&&s.includes(c.from),path);s=s.replace(c.from,c.to);}assert.equal(hash(s),r.sha256,path);}});
test('authoritative presentation moments fire once, preserve grace, catch same-tick batches, shared wins and rematch',()=>{
 const m=new Moments(),r=new OutbreakRules([0,1,2],0,{announcementTicks:1,countdownTicks:60,graceTicks:60});const cues=(tick:number)=>m.update(r.view(tick),1).map(e=>e.cue);
 assert.deepEqual(cues(0),['reveal']);assert.deepEqual(cues(0),[]);r.advanceClock(1);assert.deepEqual(cues(1),['count']);assert.deepEqual(cues(2),[]);r.advanceClock(61);assert.deepEqual(cues(61),['go']);r.infect(62,[[0,2]]);assert.deepEqual(cues(62),['last','infect']);assert.deepEqual(cues(63),[]);r.infect(123,[[0,1]]);assert.deepEqual(cues(123),['round']);assert.deepEqual(cues(124),[]);
 const two=new OutbreakRules([0,1],0,{announcementTicks:1,countdownTicks:1,graceTicks:60});two.advanceClock(2);m.reset();assert.deepEqual(m.update(two.view(2),1).map(e=>e.cue),['go','last']);for(let round=0;round<2;round++){two.infect(round?6:3,[[0,1]]);m.update(two.view(round?6:3),1);two.next(round?7:4);if(!round)two.advanceClock(6);}assert.equal(two.view(7).matchWinners.length,2);assert.deepEqual(m.update(two.view(7),1).map(e=>e.cue),['win']);assert.deepEqual(m.update(two.view(8),1),[]);m.update(undefined,1);assert.deepEqual(m.update(new OutbreakRules([0,1],0).view(0),1).map(e=>e.cue),['reveal']);
});
test('every procedural cue is short, bounded and has a nonzero repetition limit',()=>{for(const s of Object.values(SOUNDS)){assert.ok(s.cooldown>=100);assert.ok(s.notes.length<=3);for(const[a,b,len,delay=0]of s.notes){assert.ok(a>0&&b>0&&len>0&&len+delay<.6);}}});

test('sound limiter bounds bursts, important cues preempt, mute cleans voices and hidden tabs stay silent',async()=>{
 const {GameAudio}=await import('../src/presentation/audio');const oldDoc=Object.getOwnPropertyDescriptor(globalThis,'document'),oldPerformance=Object.getOwnPropertyDescriptor(globalThis,'performance');let now=1000;
 Object.defineProperty(globalThis,'document',{value:{hidden:false},configurable:true});Object.defineProperty(globalThis,'performance',{value:{now:()=>now},configurable:true});
 const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){}});const node=()=>({connect(){},disconnect(){}});const audio=new GameAudio();const ctx:any={state:'running',currentTime:0,createOscillator(){return {...node(),frequency:param(),start(){},stop(){this.onended?.();},onended:null};},createGain(){return {...node(),gain:param()};}};
 audio.context=ctx;audio.master=ctx.createGain();audio.enabled=true;
 try{for(const cue of ['jump','charge','fire','attach','miss','tension','impact','build']as const){now+=400;audio.play(cue);}assert.ok(audio.voices.size<=8);assert.ok(audio.dropped>0);now+=2000;audio.play('win');assert.ok(audio.voices.size<=8&&audio.peakVoices<=8);audio.toggle();assert.equal(audio.voices.size,0);const played=audio.played;audio.play('jump');assert.equal(audio.played,played);audio.enabled=true;(document as any).hidden=true;now+=2000;audio.play('go');assert.equal(audio.played,played);}finally{if(oldDoc)Object.defineProperty(globalThis,'document',oldDoc);else delete(globalThis as any).document;if(oldPerformance)Object.defineProperty(globalThis,'performance',oldPerformance);}
});
