import {test} from 'node:test';import assert from 'node:assert/strict';import {Vec2} from 'planck';
import {Simulation} from '../src/simulation/world';import {capture,restore} from '../src/simulation/state';import {POISON_BALANCE} from '../src/game/poison-balance';import {OutbreakRules} from '../src/game/outbreak';
function attached(dynamic:boolean,eligible?:number){const s=new Simulation();const [a,b]=s.frogs;a.body.setTransform(Vec2(dynamic?12:16,dynamic?9:11),0);b.body.setTransform(Vec2(dynamic?16:24,dynamic?9:10),0);s.setInput(0,{x:dynamic?1:0,y:dynamic?0:-1,held:true});for(let i=0;i<9;i++)s.step();assert.equal(a.tongue?.phase,'attached');a.poisonPullFromTick=eligible;for(const f of s.frogs)f.body.setLinearVelocity(Vec2(0,0));return s;}
function delta(s:Simulation){const a=s.frogs[0],v=a.body.getLinearVelocity().clone();s.pullGrapple(a);return Vec2.distance(v,a.body.getLinearVelocity());}
test('only eligible poison frogs gain 10% active acceleration, for terrain and reciprocal dynamic targets',()=>{assert.equal(POISON_BALANCE.grapplePullMultiplier,1.1);for(const dynamic of [false,true]){const safe=attached(dynamic),poison=attached(dynamic,0),grace=attached(dynamic,100);const base=delta(safe);assert.ok(Math.abs(delta(poison)/base-1.1)<1e-10);assert.equal(delta(grace),base);grace.tick=100;for(const f of grace.frogs)f.body.setLinearVelocity(Vec2(0,0));assert.ok(Math.abs(delta(grace)/base-1.1)<1e-10);if(dynamic){const[a,b]=poison.frogs;assert.ok(a.body.getLinearVelocity().x>0&&b.body.getLinearVelocity().x<0);assert.ok(Math.abs(a.body.getLinearVelocity().x+b.body.getLinearVelocity().x)<1e-10);}}});
test('unchanged radial ceiling, tangential momentum and release; no short-distance locking',()=>{for(const dynamic of [false,true]){const s=attached(dynamic,0),a=s.frogs[0],t=a.tongue!,p=a.body.getPosition(),anchor=t.target!.getWorldPoint(Vec2(t.localAnchor!.x,t.localAnchor!.y)),n=Vec2.sub(anchor,p);n.normalize();a.body.setLinearVelocity(Vec2(n.x*8,n.y*8));assert.equal(delta(s),0);a.body.setLinearVelocity(Vec2(-n.y*3,n.x*3));s.pullGrapple(a);const v=a.body.getLinearVelocity().clone();assert.ok(Math.abs(v.x*(-n.y)+v.y*n.x-3)<1e-10);s.detach(a);assert.deepEqual(a.body.getLinearVelocity(),v);}
const s=attached(true,0),[a,b]=s.frogs;b.body.setTransform(Vec2(a.body.getPosition().x+.95,a.body.getPosition().y),0);assert.equal(delta(s),0);});
test('authoritative eligibility survives snapshot/reconciliation and begins exactly at grace expiry',()=>{const rules=new OutbreakRules([0,1,2],0,{announcementTicks:1,countdownTicks:1,graceTicks:60});rules.advanceClock(2);rules.infect(3,[[0,1]]);assert.equal(rules.records[0].infectiousTick,2);assert.equal(rules.records[1].infectiousTick,63);const s=attached(true,63);s.tick=62;const client=new Simulation();restore(client,capture(s));assert.deepEqual(capture(client),capture(s));const base=delta(s);s.tick=63;client.tick=63;for(const sim of [s,client])for(const f of sim.frogs)f.body.setLinearVelocity(Vec2(0,0));assert.ok(Math.abs(delta(s)/base-1.1)<1e-10);assert.equal(delta(client),.44);});
test('poison designation never changes ungrafted movement or jump trajectories',()=>{for(const held of [false,true]){const a=new Simulation(),b=new Simulation();b.frogs[0].poisonPullFromTick=0;for(let i=0;i<90;i++){a.step();b.step();}for(let i=0;i<45;i++){const input={x:1,y:0,held:held&&i<40};a.setInput(0,input);b.setInput(0,input);a.step();b.step();assert.deepEqual(a.frogs[0].body.getPosition(),b.frogs[0].body.getPosition());assert.deepEqual(a.frogs[0].body.getLinearVelocity(),b.frogs[0].body.getLinearVelocity());}}});
test('poison pulling remains finite through repeated attach/release and sustained reciprocal contact',()=>{for(let cycle=0;cycle<12;cycle++){const s=attached(true,0);s.frogs[1].poisonPullFromTick=0;for(let i=0;i<300;i++){s.step();for(const f of s.frogs){const p=f.body.getPosition(),v=f.body.getLinearVelocity();assert.ok(Number.isFinite(p.x+p.y+v.x+v.y));assert.ok(Math.hypot(v.x,v.y)<80);}}s.detach(s.frogs[0]);s.setInput(0,{x:-1,y:0,held:false});for(let i=0;i<20;i++)s.step();assert.ok(Math.abs(s.frogs[0].body.getLinearVelocity().x)>0);}});
test('two, four and eight frogs can chase/escape and grapple without poison-only movement spikes',()=>{for(const count of [2,4,8]){const s=new Simulation();sizeSimulation(s,count);s.frogs.forEach((f,i)=>{f.body.setTransform(Vec2(6+i*3.8,10+(i%2)),0);if(i<count-1)f.poisonPullFromTick=0;});for(let tick=0;tick<1800;tick++){for(let i=0;i<count;i++){const period=tick%90;s.setInput(i,{x:i===count-1?-1:1,y:period<30?-1:0,held:period<55});}s.step();for(const f of s.frogs){const p=f.body.getPosition(),v=f.body.getLinearVelocity();assert.ok(Number.isFinite(p.x+p.y+v.x+v.y));assert.ok(Math.hypot(v.x,v.y)<80);}}}});
import {sizeSimulation} from '../src/simulation/roster';
import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {m12PreservedSource,m13PreservedSource} from './preserved-source';
test('M12 changes only the documented eligibility, snapshot and acceleration lines; all other runtime sources remain exact',()=>{const m=JSON.parse(readFileSync(new URL('../docs/milestone-12-preservation.json',import.meta.url),'utf8'));const hash=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');for(const[p,h]of Object.entries(m.protected))assert.equal(hash(m13PreservedSource(p)),h,p);for(const[p,r]of Object.entries(m.files)as[string,{sha256:string;changes:{from:string;to:string}[]}][]){let source=m13PreservedSource(p);for(const c of r.changes){assert.ok(c.from&&source.includes(c.from),p);source=source.replace(c.from,c.to);}assert.equal(hash(source),r.sha256,p);assert.equal(source,m12PreservedSource(p));}});
