import {test} from 'node:test';import assert from 'node:assert/strict';import {Vec2} from 'planck';import {Simulation} from '../src/simulation/world';import {setSimulationArena} from '../src/simulation/arena-adapter';import {capture,restore} from '../src/simulation/state';import {SURFACES,resolveSurfaces} from '../src/simulation/surfaces';import {ARENAS} from '../src/simulation/arenas';import {sizeSimulation} from '../src/simulation/roster';
function pond(x=13,y=14.8,vy=3){const s=new Simulation();setSimulationArena(s,'sunny-pond');s.frogs[0].body.setTransform(Vec2(x,y),0);s.frogs[0].body.setLinearVelocity(Vec2(0,vy));s.frogs[1].body.setTransform(Vec2(37,21.05),0);return s;}
function steps(s:Simulation,n:number){for(let i=0;i<n;i++)s.step();}
test('lily top landing gives bounded upward velocity, preserves horizontal momentum, and never launches stationary/underside/side contact',()=>{const s=pond();s.frogs[0].body.setLinearVelocity(Vec2(2,3));for(let i=0;i<20&&s.frogs[0].surfaceBounceTick===undefined;i++)s.step();const f=s.frogs[0];assert.ok(f.surfaceBounceTick!==undefined);assert.equal(f.body.getLinearVelocity().y,-12);assert.ok(f.body.getLinearVelocity().x>0&&f.body.getLinearVelocity().x<=2); // Existing contact friction may reduce lateral speed; bounce adds no lateral impulse.
assert.equal(f.grounded,false);assert.equal(f.coyote,0);const tick=f.surfaceBounceTick;steps(s,10);assert.equal(f.surfaceBounceTick,tick);
 const underside=pond(13,16.8,-4);steps(underside,4);assert.equal(underside.frogs[0].surfaceBounceTick,undefined);const side=pond(10.5,16,0);side.frogs[0].body.setLinearVelocity(Vec2(3,0));steps(side,5);assert.equal(side.frogs[0].surfaceBounceTick,undefined);});
test('mud slows grounded control to 4.5 and leaving/jumping immediately restores normal movement',()=>{const s=pond(5,17.2,0);steps(s,20);const f=s.frogs[0];assert.equal(f.stickyMud,true);s.setInput(0,{x:1,y:0,held:false});steps(s,8);assert.ok(Math.abs(f.body.getLinearVelocity().x-4.5)<.1);f.body.setTransform(Vec2(12,19),0);steps(s,1);assert.equal(f.stickyMud,undefined);f.body.setTransform(Vec2(20,21.05),0);f.body.setLinearVelocity(Vec2(0,0));steps(s,6);steps(s,10);assert.ok(Math.abs(f.body.getLinearVelocity().x-6)<.1);
 f.body.setTransform(Vec2(5,17.2),0);f.body.setLinearVelocity(Vec2(0,0));steps(s,10);s.setInput(0,{x:1,y:0,held:true});steps(s,1);s.setInput(0,{x:1,y:0,held:false});steps(s,1);assert.equal(f.stickyMud,undefined);assert.ok(f.body.getLinearVelocity().y< -8);});
test('simultaneous pad arrivals independently bounce all players; snapshot preserves events and prediction stays identical',()=>{const s=pond();sizeSimulation(s,8);s.frogs.forEach((f,i)=>{f.body.setTransform(Vec2(i<4?11.5+i*.95:25.5+(i-4)*.95,14.8),0);f.body.setLinearVelocity(Vec2(0,3));});steps(s,12);assert.ok(s.frogs.every(f=>f.surfaceBounceTick!==undefined));const client=new Simulation();setSimulationArena(client,'sunny-pond');restore(client,capture(s));assert.deepEqual(capture(client),capture(s));for(let i=0;i<5;i++){s.step();client.step();for(let j=0;j<8;j++)assert.ok(Vec2.distance(s.frogs[j].body.getPosition(),client.frogs[j].body.getPosition())<.06);}});
test('only sunny pond has special materials and tuning remains conservative',()=>{for(const id of ['canopy','swingworks']as const)assert.ok(ARENAS[id].solids.every(r=>!r.surface));assert.equal(SURFACES.lilyLaunchSpeed,12);assert.equal(SURFACES.mudGroundSpeedMultiplier,.75);assert.equal(ARENAS['sunny-pond'].solids.filter(r=>r.surface==='lily').length,2);assert.equal(ARENAS['sunny-pond'].solids.filter(r=>r.surface==='mud').length,2);});

test('bounce adds only vertical impulse and existing terrain/frog grapples remain physical through landing/release',()=>{const s=pond();const f=s.frogs[0];for(let i=0;i<20&&f.surfaceBounceTick===undefined;i++)s.step();f.surfaceBounceTick=undefined;f.body.setLinearVelocity(Vec2(3,0));resolveSurfaces(s,[{down:3,position:f.body.getPosition().clone()},{down:0,position:s.frogs[1].body.getPosition().clone()}]);assert.equal(f.body.getLinearVelocity().x,3);assert.equal(f.body.getLinearVelocity().y,-12);for(const target of ['terrain','frog']){const a=pond(13,13,3),b=a.frogs[1];b.body.setTransform(Vec2(16,13),0);a.setInput(0,{x:target==='frog'?1:0,y:target==='terrain'?-1:0,held:true});for(let i=0;i<180;i++){a.step();for(const q of a.frogs){const p=q.body.getPosition(),v=q.body.getLinearVelocity();assert.ok(Number.isFinite(p.x+p.y+v.x+v.y));assert.ok(Math.hypot(v.x,v.y)<80);}}const v=a.frogs[0].body.getLinearVelocity().clone();a.detach(a.frogs[0]);assert.deepEqual(a.frogs[0].body.getLinearVelocity(),v);}});
import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {m13PreservedSource} from './preserved-source';
test('M13 preserves approved balance/input/camera/sounds/old arena bytes outside documented localized surface/map adapters',()=>{const m=JSON.parse(readFileSync(new URL('../docs/milestone-13-preservation.json',import.meta.url),'utf8'));const hash=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');for(const[p,h]of Object.entries(m.protected))assert.equal(hash(readFileSync(new URL(`../${p}`,import.meta.url))),h,p);for(const[p,r]of Object.entries(m.files)as[string,{sha256:string;changes:{from:string;to:string}[]}][]){let s=readFileSync(new URL(`../${p}`,import.meta.url),'utf8');for(const c of r.changes){assert.ok(c.from&&s.includes(c.from),p);s=s.replace(c.from,c.to);}assert.equal(hash(s),r.sha256,p);assert.equal(s,m13PreservedSource(p));}});
test('standing lily contact does not auto-repeat; mud underside and frog-supported contacts do not slow; reset clears material state',()=>{const s=pond(13,15.3,0);steps(s,5);assert.equal(s.frogs[0].surfaceBounceTick,undefined);const a=pond(5,18.8,-4);steps(a,3);assert.equal(a.frogs[0].stickyMud,undefined);s.frogs[0].stickyMud=true;s.frogs[0].surfaceBounceTick=1;s.reset();assert.equal(s.frogs[0].stickyMud,undefined);assert.equal(s.frogs[0].surfaceBounceTick,undefined);});
import {RopeJoint} from 'planck';
test('landing while already attached to terrain or a moving frog bounces without detaching/locking or changing release momentum',()=>{for(const dynamic of [false,true]){const s=pond(13,15.25,4),f=s.frogs[0],b=s.frogs[1];let target=b.body,local=Vec2(0,0);if(dynamic){b.body.setTransform(Vec2(16,15.25),0);b.body.setLinearVelocity(Vec2(-1,4));}else{for(let q=s.world.getBodyList();q;q=q.getNext())if(!q.isDynamic()&&q.getPosition().x===20&&q.getPosition().y===11.5){target=q;local=Vec2(-3,.25);break;}assert.equal(target.isDynamic(),false);}const anchor=target.getWorldPoint(local);f.tongue={phase:'attached',direction:{x:1,y:0},tip:{...anchor},distance:0,length:8,target,localAnchor:{...local},joint:s.world.createJoint(new RopeJoint({maxLength:8,collideConnected:true,bodyA:f.body,bodyB:target,localAnchorA:Vec2(0,0),localAnchorB:local}))!};f.held=true;f.input={x:0,y:0,held:true};steps(s,3);assert.ok(f.surfaceBounceTick!==undefined);assert.equal(f.tongue?.phase,'attached');for(let i=0;i<90;i++){s.step();for(const q of s.frogs){const v=q.body.getLinearVelocity();assert.ok(Number.isFinite(v.x+v.y)&&Math.hypot(v.x,v.y)<80);}}const v=f.body.getLinearVelocity().clone();s.detach(f);assert.deepEqual(f.body.getLinearVelocity(),v);}});
test('a valid buffered normal jump takes priority over automatic lily bounce',()=>{const s=pond(13,15.25,4),f=s.frogs[0];f.bufferedRelease={remaining:.1,x:0,charge:0};steps(s,1);assert.equal(f.surfaceBounceTick,undefined);assert.equal(f.body.getLinearVelocity().y,-9.5);});
