import {modifier,type ModifierId} from '../chaos/registry';
import type {Connection} from '../network/client';
import './chaos-ui.css';
/** Screen-space presentation only; no touch/viewport ownership changes. */
export class ChaosUI{
 panel=document.createElement('section');strip=document.createElement('div');toggle=document.createElement('button');signature='';
 constructor(private net:Connection){this.panel.id='chaos-voting';this.panel.hidden=true;this.panel.setAttribute('aria-label','Chaos Voting');document.querySelector('#results')!.after(this.panel);this.strip.id='chaos-active';document.querySelector('#session')!.append(this.strip);this.toggle.id='chaos-toggle';this.toggle.onclick=()=>net.room?.send('select-chaos',!net.lobby?.chaosEnabled);document.querySelector('.lobby-primary')!.after(this.toggle);const note=document.createElement('p');note.className='chaos-lobby-note';note.textContent='Round 1 is normal. Vote between rounds; up to 3 effects rotate. Changing Chaos clears Ready.';this.toggle.after(note);}
 update(){const {lobby,chaos:c,playerId,status}=this.net;this.toggle.textContent=`Chaos Voting: ${lobby?.chaosEnabled===false?'Off':'On'}`;this.toggle.setAttribute('aria-pressed',String(lobby?.chaosEnabled!==false));this.toggle.disabled=!lobby||lobby.phase!=='lobby'||lobby.hostId!==playerId||status!=='connected';
  const voting=lobby?.phase==='game'&&!!c&&c.phase!=='idle';this.panel.hidden=!voting;this.strip.hidden=lobby?.phase!=='game'||!c?.enabled;this.strip.textContent=c?.enabled?(c.active.length?`CHAOS · ${c.active.map(id=>modifier(id).name).join(' + ')}`:'CHAOS · Round 1: normal physics'):'';
  if(!voting||!c)return;document.querySelector<HTMLElement>('#results')!.hidden=true;document.querySelector<HTMLElement>('#session')!.hidden=true;
  const signature=JSON.stringify([c,playerId,status]);if(signature!==this.signature){this.signature=signature;this.panel.replaceChildren();const heading=document.createElement('h2');heading.textContent=c.phase==='voting'?'Choose the next chaos':'The pond has spoken!';this.panel.append(heading);const timer=document.createElement('strong');timer.id='chaos-timer';this.panel.append(timer);
   const keeping=document.createElement('p');keeping.textContent=`Keeping: ${c.active.filter(id=>c.phase==='reveal'||id!==c.expiring).map(id=>modifier(id).name).join(' + ')||'normal physics'}`;this.panel.append(keeping);
   if(c.expiring){const expired=document.createElement('p');expired.className='chaos-expiring';expired.textContent=`${c.phase==='reveal'?c.winner===c.expiring?'RENEWED':'EXPIRED':'EXPIRING'}: ${modifier(c.expiring).name} · vote for it below to renew it as the newest effect.`;this.panel.append(expired);}
   const cards=document.createElement('div');cards.className='chaos-cards';for(const id of c.phase==='reveal'&&c.winner?[c.winner]:c.choices){const m=modifier(id),card=document.createElement('button');card.className='chaos-card';card.dataset.modifier=id;card.setAttribute('aria-pressed',String(c.votes[playerId]===id));card.disabled=c.phase!=='voting'||status!=='connected';const title=document.createElement('strong');title.textContent=`${m.icon} ${m.name}${id===c.expiring?' · RENEW':''}`;const desc=document.createElement('span');desc.textContent=m.description;const count=document.createElement('small');count.textContent=c.phase==='voting'?`${c.counts[c.choices.indexOf(id)]??0} votes · tie priority ${c.priority.indexOf(id)+1}`:'ACTIVE NEXT ROUND';card.append(title,desc,count);card.onclick=()=>this.net.room?.send('chaos-vote',{ballotId:c.ballotId,id:id as ModifierId});cards.append(card);}this.panel.append(cards);const note=document.createElement('p');note.textContent=c.notice||'One vote each. Change your choice until time runs out. Lower tie priority number wins ties.';this.panel.append(note);
  }
  const timer=this.panel.querySelector('#chaos-timer');if(timer)timer.textContent=c.phase==='voting'?`${Math.max(0,Math.ceil((c.closesAt-Date.now()-this.net.offset)/1000))} seconds`:'Get ready…';
 }
}
