import type {OutbreakView} from '../game/outbreak';
const el=(id:string)=>document.getElementById(id)!;const points=(n:number)=>n.toFixed(1);
function clock(ms:number){const seconds=Math.ceil(ms/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
/** Shared existing screen-space containers; no viewport or input ownership changes. */
export function renderFreezeHUD(state:OutbreakView,local:number,name:(i:number)=>string,host:boolean,connected:boolean){const freeze=state.freeze!,intro=['announcement','countdown'].includes(state.phase),final=state.phase==='match-results',results=final||state.phase==='round-results';document.body.dataset.outbreakPhase=state.phase;el('phase-overlay').hidden=!intro;el('phase-overlay').dataset.phase=state.phase;el('reveal-name').textContent=name(freeze.freezer);el('countdown-number').textContent=state.phase==='countdown'?String(Math.max(1,Math.ceil(state.remainingMs/1000))):'❄';el('outbreak-heading').textContent=`Round ${state.round}/${state.roundCount}`;el('phase-message').textContent=intro?`FREEZER — ${name(freeze.freezer)}`:state.phase==='playing'?'FREEZE TAG — Touch teammates to rescue':'';el('round-timer').textContent=clock(state.phase==='playing'?state.remainingMs:Math.max(0,60000-state.elapsedMs));const runners=state.players.length-1,active=freeze.frozen.filter(Boolean).length;el('healthy-count').textContent=state.phase==='playing'?`${runners-active}/${runners} RUNNERS MOVING`:'';
 const me=state.players[local];el('live-score').textContent=local===freeze.freezer?`FREEZER · ${freeze.freezeCount} freezes`:freeze.frozen[local]?'FROZEN · TEAMMATE RESCUE ONLY':me?`UNFROZEN · ${points(me.survivalPoints)} pts`:'';el('infection-feedback').textContent=freeze.protectedUntil[local]>state.tick?`RESCUED · ${((freeze.protectedUntil[local]-state.tick)/60).toFixed(1)}s protection`:'';if(!results)return;
 el('results-context').textContent=final?`${state.roundCount} rounds · Everyone was freezer once`:`Round ${state.round} of ${state.roundCount}`;el('results-title').textContent=final?'MATCH COMPLETE':'FREEZE TAG COMPLETE!';const winners=final?state.matchWinners:state.roundWinners;el('winner-message').textContent=`${final?'Winner':freeze.reason==='timeout'?'Escaped':'Freezer wins'}${winners.length>1?'s':''}: ${winners.map(name).join(', ')}`;const table=el('standings');table.replaceChildren();const header=document.createElement('tr');for(const title of final?['Placement','Player','Total points']:['Player','Unfrozen survival','Freezes','Clear bonus','Round score','Total points']){const th=document.createElement('th');th.textContent=title;header.append(th);}table.append(header);
 for(const p of [...state.players].sort((a,b)=>(final?b.totalPoints-a.totalPoints:(b.roundPoints??0)-(a.roundPoints??0))||a.slot-b.slot)){const row=document.createElement('tr');if(winners.includes(p.slot))row.className='winner-row';const label=name(p.slot)+(p.slot===freeze.freezer?' · Freezer':'');for(const text of final?[`${p.finalPlace}${state.players.some(o=>o.slot!==p.slot&&o.finalPlace===p.finalPlace)?' (tied)':''}`,label,points(p.totalPoints)]:[label,points(p.survivalPoints),points(p.slot===freeze.freezer?freeze.freezePoints:0),points(p.slot===freeze.freezer?freeze.clearBonus:0),points(p.roundPoints??0),points(p.totalPoints)]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}table.append(row);}
 el('next-round').hidden=final||!host;el('return-lobby').hidden=!final||!host;el('next-round').textContent=state.round===state.roundCount?'Final Standings':'Next Round';el('results-help').textContent=host?(final?'Return to the lobby for rematch or choose another mode.':'Continue when everyone has reviewed the results.'):'Waiting for the host to continue.';for(const id of ['next-round','return-lobby'])(el(id)as HTMLButtonElement).disabled=!connected;
}
