import {MODES,type GameMode} from '../game/modes';
import type {LobbyState} from '../network/protocol';
export class ModeUI {
 private select:HTMLSelectElement;private note:HTMLElement;
 constructor(send:(mode:GameMode)=>void){const panel=document.createElement('div');panel.className='mode-choice';panel.innerHTML='<label for="mode-select">Game mode</label><select id="mode-select"></select><p id="mode-description"></p>';document.querySelector('.lobby-primary')!.before(panel);this.select=panel.querySelector('select')!;this.note=panel.querySelector('p')!;for(const mode of MODES){const option=document.createElement('option');option.value=mode.id;option.textContent=mode.name;this.select.append(option);}this.select.onchange=()=>send(this.select.value as GameMode);
  for(const target of ['#guide-content','#help-content']){const details=document.createElement('details');details.className='freeze-help';details.innerHTML='<summary>Freeze Tag rules</summary><p>One freezer tags bodies to freeze frogs. Unfrozen runners touch frozen teammates to rescue them. Tongues never freeze or rescue. No automatic thaw.</p><p>60 seconds, or until all runners freeze. With two players, the first freeze ends the round. Rescue grants 1 second of protection.</p><p>Runners: 1 point/second unfrozen. Freezer: 3 points/freeze + 5 for freezing everyone with 3–8 players. Everyone starts freezer once. Highest match points wins; ties share victory.</p>';document.querySelector(target)!.append(details);}
 }
 update(lobby:LobbyState|undefined,local:string,connected:boolean){const freeze=lobby?.mode==='freeze';this.select.value=freeze?'freeze':'poison';this.select.disabled=!lobby||lobby.hostId!==local||lobby.phase!=='lobby'||!connected;this.note.textContent=freeze?'60 seconds · rescue teammates by body contact · no automatic thaw. Two players: first freeze ends the round.':'Survive spreading poison · tongues never spread poison.';document.querySelector('#start')!.textContent=freeze?'Start Freeze Tag':'Start Poison Tag';document.querySelector('#phase-overlay .eyebrow')!.textContent=freeze?'THE FREEZER':'POISON DART FROG';document.querySelector('#phase-overlay small')!.textContent=freeze?'Dodge the freezer. Touch teammates to rescue.':'Body contact spreads poison. Tongues don’t.';document.querySelector('.pond-reveal-caption')!.textContent=freeze?'BIG CHILL. LITTLE FROGS.':'TINY FROG. BIG DART ENERGY.';document.querySelector('#game-help')!.textContent=freeze?'Body contact freezes/rescues. Frozen? Wait for a teammate. No automatic thaw.':'WASD/Arrow keys + Space · Tap/release = jump; hold/release = charge. In air, hold = grapple; release = detach. Body contact only. GRACE cannot spread poison for 1 second.';}
}
