import {DT} from '../simulation/config';
import {OUTBREAK,type OutbreakPhase,type OutbreakView} from './outbreak';
export const CLASSIC={...OUTBREAK,roundTicks:3600,graceTicks:60,pointsPerSecond:1};
export type ClassicDetails={it:number;protectedUntil:number;transfers:number;notItMs:number[];itMs:number[]};
/** One authoritative transfer per tick; contacts and body centres come from the server simulation. */
export class ClassicRules {
 phase:OutbreakPhase='announcement';round=0;phaseEndsTick=0;startedTick:number|null=null;stoppedTick:number|null=null;lastTick=0;
 records:{activeTicks:number;infectiousTick:null}[]=[];totals:number[];roundWinners:number[]=[];it=0;protectedUntil=0;transfers=0;
 constructor(readonly order:number[],tick:number,readonly timing=CLASSIC){if(order.length<2||order.length>8||new Set(order).size!==order.length||order.some(i=>!Number.isInteger(i)||i<0||i>=order.length))throw Error('Starting IT order must be a permutation of 2–8 roster slots');this.order=[...order];this.totals=Array(order.length).fill(0);this.beginRound(tick);}
 get patientZero(){return this.order[this.round];}
 beginRound(tick:number){this.phase='announcement';this.phaseEndsTick=tick+this.timing.announcementTicks;this.startedTick=null;this.stoppedTick=null;this.lastTick=tick;this.it=this.patientZero;this.protectedUntil=0;this.transfers=0;this.roundWinners=[];this.records=this.order.map(()=>({activeTicks:0,infectiousTick:null}));}
 advanceClock(tick:number){if(this.phase==='announcement'&&tick>=this.phaseEndsTick){this.phase='countdown';this.phaseEndsTick+=this.timing.countdownTicks;}if(this.phase==='countdown'&&tick>=this.phaseEndsTick){this.phase='playing';this.startedTick=tick;this.lastTick=tick;}}
 infect(tick:number,contacts:readonly(readonly[number,number])[],positions:readonly{x:number;y:number}[]=[]){if(this.phase!=='playing'||this.startedTick===null)return [];const deadline=this.startedTick+this.timing.roundTicks,end=Math.min(tick,deadline),delta=Math.max(0,end-this.lastTick);this.records.forEach((p,i)=>{if(i!==this.it)p.activeTicks+=delta;});this.lastTick=end;if(tick>=deadline){this.finish(deadline);return [];}if(tick<this.protectedUntil)return [];
  const targets=new Set<number>();for(const [a,b]of contacts){const target=a===this.it?b:b===this.it?a:-1;if(target>=0&&target!==this.it&&this.records[target])targets.add(target);}
  const centre=positions[this.it],distance=(i:number)=>centre&&positions[i]?(positions[i].x-centre.x)**2+(positions[i].y-centre.y)**2:0;
  const target=[...targets].sort((a,b)=>distance(a)-distance(b)||a-b)[0];if(target===undefined)return [];this.it=target;this.protectedUntil=tick+this.timing.graceTicks;this.transfers++;return [target];
 }
 points(slot:number){return Math.floor(this.records[slot].activeTicks*DT*this.timing.pointsPerSecond*10+1e-9)/10;}
 finish(tick:number){this.phase='round-results';this.stoppedTick=tick;const best=Math.max(...this.records.map((_,i)=>this.points(i)));this.roundWinners=this.records.flatMap((_,i)=>this.points(i)===best?[i]:[]);this.records.forEach((_,i)=>this.totals[i]=Math.round((this.totals[i]+this.points(i))*10)/10);}
 next(tick:number){if(this.phase!=='round-results')return false;if(this.round+1===this.order.length){this.phase='match-results';return true;}this.round++;this.beginRound(tick);return true;}
 view(tick:number):OutbreakView{const elapsed=this.startedTick===null?0:Math.max(0,(this.stoppedTick??tick)-this.startedTick)*DT*1000,highest=Math.max(...this.totals);return {mode:'classic',classic:{it:this.it,protectedUntil:this.protectedUntil,transfers:this.transfers,notItMs:this.records.map(p=>p.activeTicks*DT*1000),itMs:this.records.map(p=>Math.max(0,elapsed-p.activeTicks*DT*1000))},phase:this.phase,round:this.round+1,roundCount:this.order.length,patientZero:this.patientZero,patientZeroOrder:[...this.order],tick,elapsedMs:elapsed,remainingMs:this.phase==='playing'?Math.max(0,this.startedTick!+this.timing.roundTicks-tick)*DT*1000:['announcement','countdown'].includes(this.phase)?Math.max(0,this.phaseEndsTick-tick)*DT*1000:0,players:this.records.map((p,slot)=>({slot,state:'healthy',patientZero:slot===this.patientZero,infectedTick:null,infectiousTick:null,infectionPlace:null,roundPoints:this.stoppedTick===null?null:this.points(slot),survivalMs:p.activeTicks*DT*1000,survivalPoints:this.points(slot),placementBonus:0,totalPoints:this.totals[slot],finalPlace:1+this.totals.filter(n=>n>this.totals[slot]).length})),roundWinners:[...this.roundWinners],matchWinners:this.phase==='match-results'?this.totals.flatMap((n,i)=>n===highest?[i]:[]):[]};}
}
