import {DT} from '../simulation/config';
import {OUTBREAK,type OutbreakPhase,type OutbreakView} from './outbreak';
export const FREEZE={...OUTBREAK,roundTicks:3600,protectionTicks:60,pointsPerSecond:1,freezePoints:3,clearBonus:5};
export type FreezeDetails={freezer:number;frozen:boolean[];protectedUntil:number[];freezeCount:number;rescueCounts:number[];freezePoints:number;clearBonus:number;reason:'all-frozen'|'timeout'|null};
type Record={frozen:boolean;protectedUntil:number;activeTicks:number;rescues:number;infectiousTick:null};
/** Deterministic mode rules; only authoritative body-contact pairs are accepted. No automatic thaw. */
export class FreezeRules {
 phase:OutbreakPhase='announcement';round=0;phaseEndsTick=0;startedTick:number|null=null;stoppedTick:number|null=null;lastTick=0;
 records:Record[]=[];totals:number[];roundWinners:number[]=[];freezeCount=0;clearBonus=0;reason:FreezeDetails['reason']=null;
 constructor(readonly order:number[],tick:number,readonly timing=FREEZE){if(order.length<2||order.length>8||new Set(order).size!==order.length||order.some(i=>!Number.isInteger(i)||i<0||i>=order.length))throw Error('Freezer order must be a permutation of 2–8 roster slots');this.order=[...order];this.totals=Array(order.length).fill(0);this.beginRound(tick);}
 get patientZero(){return this.order[this.round];}get frozen(){return this.records.map(p=>p.frozen);}
 beginRound(tick:number){this.phase='announcement';this.phaseEndsTick=tick+this.timing.announcementTicks;this.startedTick=null;this.stoppedTick=null;this.lastTick=tick;this.freezeCount=0;this.clearBonus=0;this.reason=null;this.roundWinners=[];this.records=this.order.map(()=>({frozen:false,protectedUntil:0,activeTicks:0,rescues:0,infectiousTick:null}));}
 advanceClock(tick:number){if(this.phase==='announcement'&&tick>=this.phaseEndsTick){this.phase='countdown';this.phaseEndsTick+=this.timing.countdownTicks;}if(this.phase==='countdown'&&tick>=this.phaseEndsTick){this.phase='playing';this.startedTick=tick;this.lastTick=tick;}}
 infect(tick:number,contacts:readonly(readonly[number,number])[]){if(this.phase!=='playing'||this.startedTick===null)return [];const deadline=this.startedTick+this.timing.roundTicks,end=Math.min(tick,deadline),delta=Math.max(0,end-this.lastTick);this.records.forEach((p,i)=>{if(i!==this.patientZero&&!p.frozen)p.activeTicks+=delta;});this.lastTick=end;
  // At the exact deadline no new tags: the completed interval determines the timeout outcome.
  if(tick>=deadline){this.finish(deadline,'timeout');return [];}
  const before=this.frozen,newly=new Set<number>();for(const [a,b]of contacts){if(a===b||!this.records[a]||!this.records[b])continue;const target=a===this.patientZero?b:b===this.patientZero?a:-1;if(target>=0&&!before[target]&&tick>=this.records[target].protectedUntil)newly.add(target);}
  const batch=[...newly].sort((a,b)=>a-b);for(const i of batch)this.records[i].frozen=true;this.freezeCount+=batch.length;
  const rescues=new Map<number,number>();for(const [a,b]of contacts)for(const [target,helper]of [[a,b],[b,a]]){if(!this.records[target]||!this.records[helper]||target===helper||helper===this.patientZero||target===this.patientZero||!before[target]||before[helper]||newly.has(helper))continue;const previous=rescues.get(target);if(previous===undefined||helper<previous)rescues.set(target,helper);}
  for(const [i,helper]of rescues){this.records[i].frozen=false;this.records[i].protectedUntil=tick+this.timing.protectionTicks;this.records[helper].rescues++;}
  if(this.records.every((p,i)=>i===this.patientZero||p.frozen))this.finish(tick,'all-frozen');return batch;
 }
 points(slot:number){return slot===this.patientZero?this.freezeCount*this.timing.freezePoints+this.clearBonus:Math.floor(this.records[slot].activeTicks*DT*this.timing.pointsPerSecond*10+1e-9)/10;}
 finish(tick:number,reason:FreezeDetails['reason']){this.phase='round-results';this.stoppedTick=tick;this.reason=reason;if(reason==='all-frozen'){this.clearBonus=this.order.length>2?this.timing.clearBonus:0;this.roundWinners=[this.patientZero];}else this.roundWinners=this.records.flatMap((p,i)=>i!==this.patientZero&&!p.frozen?[i]:[]);this.records.forEach((_,i)=>this.totals[i]=Math.round((this.totals[i]+this.points(i))*10)/10);}
 next(tick:number){if(this.phase!=='round-results')return false;if(this.round+1===this.order.length){this.phase='match-results';return true;}this.round++;this.beginRound(tick);return true;}
 view(tick:number):OutbreakView{const highest=Math.max(...this.totals),active=this.startedTick!==null;return {mode:'freeze',freeze:{freezer:this.patientZero,frozen:this.frozen,protectedUntil:this.records.map(p=>p.protectedUntil),freezeCount:this.freezeCount,rescueCounts:this.records.map(p=>p.rescues),freezePoints:this.freezeCount*this.timing.freezePoints,clearBonus:this.clearBonus,reason:this.reason},phase:this.phase,round:this.round+1,roundCount:this.order.length,patientZero:this.patientZero,patientZeroOrder:[...this.order],tick,elapsedMs:active?Math.max(0,(this.stoppedTick??tick)-this.startedTick!)*DT*1000:0,remainingMs:this.phase==='playing'?Math.max(0,this.startedTick!+this.timing.roundTicks-tick)*DT*1000:['announcement','countdown'].includes(this.phase)?Math.max(0,this.phaseEndsTick-tick)*DT*1000:0,players:this.records.map((p,slot)=>({slot,state:'healthy',patientZero:slot===this.patientZero,infectedTick:null,infectiousTick:null,infectionPlace:null,roundPoints:this.stoppedTick===null?null:this.points(slot),survivalMs:p.activeTicks*DT*1000,survivalPoints:slot===this.patientZero?0:this.points(slot),placementBonus:slot===this.patientZero?this.clearBonus:0,totalPoints:this.totals[slot],finalPlace:1+this.totals.filter(n=>n>this.totals[slot]).length})),roundWinners:[...this.roundWinners],matchWinners:this.phase==='match-results'?this.totals.flatMap((n,i)=>n===highest?[i]:[]):[]};}
}
