import express from 'express';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {Server} from '@colyseus/core';
import {WebSocketTransport} from '@colyseus/ws-transport';
import {SpikeRoom} from './room';
import {StressRoom} from './stress-room';
import {partyRooms} from './party-room';
import {OutbreakRoom} from './outbreak-room';
const app=express();const http=createServer(app);
app.get('/api/rooms/:code',(req,res)=>{const code=req.params.code.trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){res.status(400).json({error:'Enter a six-character room code.'});return;}const room=partyRooms.get(code);if(!room){res.status(404).json({error:'Room not found. Check the code with your friend.'});return;}if(room.phase!=='lobby'){res.status(409).json({error:'This room is already playing. New players can join in the lobby only.'});return;}if(room.players.size>=8){res.status(409).json({error:'This room is full (8 players).'});return;}res.json({roomId:room.roomId,code});});
app.get('/health',(_req,res)=>res.json({ok:true,milestone:4}));
app.use(express.static(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../dist')));
const game=new Server({transport:new WebSocketTransport({server:http,pingInterval:5000,pingMaxRetries:3,maxPayload:16384})});
game.define('frog_party',OutbreakRoom);
if(process.env.ENABLE_TESTS==='1')game.define('physics_spike',SpikeRoom);
if(process.env.ENABLE_STRESS==='1')game.define('physics_stress',StressRoom);
const port=Number(process.env.PORT??2567);
await game.listen(port,process.env.HOST??'0.0.0.0');
console.log(`Frog network spike listening on ${port}`);
