// Isolated, local headless-browser integration tests, never the user's browser.
const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium');
const {spawn}=require('node:child_process'),fs=require('node:fs');
(async()=>{binary.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,PORT:'2867',HOST:'127.0.0.1',ENABLE_TESTS:'1'}});let log='';server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);let browser;
try{
 await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(log.includes('listening')){clearInterval(timer);resolve();}},50);setTimeout(()=>{clearInterval(timer);reject(Error(log));},10000);});
 browser=await chromium.launch({executablePath:await binary.executablePath(),headless:true,args:[...binary.args,'--no-sandbox','--disable-dev-shm-usage']});
 const errors=[],results=[];
 for(const lag of [50,100,150]){
 const a=await browser.newContext({viewport:{width:1280,height:900}}),b=await browser.newContext({viewport:{width:1280,height:900}});const p=await a.newPage(),q=await b.newPage();p.on('pageerror',e=>errors.push(e.message));q.on('pageerror',e=>errors.push(e.message));
 await p.goto(`http://127.0.0.1:2867/?lag=${lag}&jitter=10`);await p.locator('#name').fill('Browser A');await p.locator('#create').click();await p.locator('#code').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('#code').textContent.length===6);const code=await p.locator('#code').textContent();
 await q.goto(`http://127.0.0.1:2867/?code=${code}&lag=${lag}&jitter=10`);await q.locator('#name').fill('Browser B');await q.locator('#join').click();await q.locator('#ready').waitFor({state:'visible'});await p.locator('#ready').click();await q.locator('#ready').click();await p.locator('#start').click();
 await p.waitForFunction(()=>window.spikeDebug?.slot===0&&window.spikeDebug.playing&&window.spikeDebug.snapshots.length>5);await q.waitForFunction(()=>window.spikeDebug?.slot===1&&window.spikeDebug.playing&&window.spikeDebug.snapshots.length>5);
 const box=await p.locator('canvas').boundingBox();if(!box||box.width<300||box.height<200)throw Error('arena hidden/zero-sized after lobby transition: '+JSON.stringify({box,dom:await p.locator('#session').innerHTML()}));
 await p.locator('canvas').click();await p.keyboard.down('KeyD');await p.keyboard.down('Space');await p.waitForTimeout(300);await p.keyboard.up('KeyD');await p.waitForTimeout(700);const charging=await p.evaluate(()=>window.spikeDebug.predictor.sim.frogs[window.spikeDebug.slot].charging);await p.keyboard.up('Space');await p.waitForTimeout(80);const jump=await p.evaluate(()=>window.spikeDebug.predictor.sim.frogs[window.spikeDebug.slot].body.getLinearVelocity().y);
 await p.keyboard.down('KeyW');await p.keyboard.down('Space');await p.waitForTimeout(500);const terrainAttached=await p.evaluate(()=>{const t=window.spikeDebug.predictor.sim.frogs[window.spikeDebug.slot].tongue;return t?.phase==='attached'&&!t.target.isDynamic();});if(!terrainAttached)throw Error('browser terrain grapple failed');await p.keyboard.down('KeyD');await p.waitForTimeout(300);await p.keyboard.up('Space');await p.keyboard.up('KeyW');await p.keyboard.up('KeyD');await p.waitForTimeout(100);const released=await p.evaluate(()=>!window.spikeDebug.predictor.sim.frogs[window.spikeDebug.slot].tongue);if(!released)throw Error('browser release failed');
 const identity=await p.evaluate(()=>({id:window.spikeDebug.playerId,slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId}));await p.reload();await p.waitForFunction(()=>window.spikeDebug?.status==='connected'&&window.spikeDebug.snapshots.length>5);const restored=await p.evaluate(()=>({id:window.spikeDebug.playerId,slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId}));if(JSON.stringify(identity)!==JSON.stringify(restored))throw Error('reload spawned duplicate/changed identity');
 await p.locator('canvas').click();await p.keyboard.down('KeyA');await p.waitForTimeout(300);await p.keyboard.up('KeyA');await p.waitForTimeout(200);const acknowledged=await p.evaluate(()=>window.spikeDebug.snapshots.at(-1).ack[0]);if(acknowledged<5)throw Error('inputs not accepted after reload');
 const downloadPromise=p.waitForEvent('download');await p.locator('#export').click();const download=await downloadPromise;const diagnostics=JSON.parse(fs.readFileSync(await download.path(),'utf8'));if(diagnostics.milestone!==4||diagnostics.slot!==0||'token'in diagnostics)throw Error('invalid diagnostics export');
 const first=await p.evaluate(()=>({slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId,rtt:window.spikeDebug.rtt,pending:window.spikeDebug.predictor.pending.length,snaps:window.spikeDebug.predictor.snaps}));const second=await q.evaluate(()=>({slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId,rtt:window.spikeDebug.rtt}));if(!charging||jump>=-10||first.slot===second.slot||first.room!==second.room)throw Error(JSON.stringify({charging,jump,first,second}));
 results.push({lag,code,charging,jump,terrainAttached,released,reloadIdentityRestored:true,diagnosticsExportPassed:true,postReloadAcknowledgement:acknowledged,canvas:box,first,second,status:await p.locator('#status').textContent()});
 await p.locator('#leave').click();await q.locator('#lobby').waitFor({state:'visible'});await q.locator('#leave').click();await p.goto('about:blank');await q.goto('about:blank');
 }
 fs.writeFileSync('docs/results/browser-milestone-4.json',JSON.stringify({environment:'Two isolated local headless Chromium contexts; not separate physical devices or human acceptance',results,errors},null,2));console.log(JSON.stringify({results,errors}));if(errors.length)throw Error('browser runtime errors');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
