// Local real Phaser/WebSocket UI check; phone sizes are emulation, not physical certification.
const {chromium}=require('playwright-core'),bin=require('@sparticuz/chromium'),{spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{bin.setGraphicsMode=false;const port=3241,server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ENABLE_TESTS:'1'}});let log='',browser;server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);const checks=[],errors=[],layouts=[];const pass=s=>{checks.push(s);console.log('PASS '+s);};try{
 await new Promise((r,j)=>{let t=setInterval(()=>{if(log.includes('listening')){clearInterval(t);r();}},20);setTimeout(()=>{clearInterval(t);j(Error(log));},10000);});
 browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH||await bin.executablePath(),args:[...bin.args,'--no-sandbox','--disable-dev-shm-usage'],headless:true});const pages=[];
 const configs=[{viewport:{width:1280,height:900}},{viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:3},{viewport:{width:667,height:375},isMobile:true,hasTouch:true,deviceScaleFactor:2},{viewport:{width:1024,height:768}}];
 for(const [i,cfg]of configs.entries()){const ctx=await browser.newContext(cfg),p=await ctx.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${port}`);assert.ok(!(await p.locator('body').innerText()).match(/patient zero|outbreak|infect|healthy/i));await p.locator('#home-help').click();await p.locator('#help-dialog').waitFor({state:'visible'});assert.match(await p.locator('#help-content').innerText(),/Poison Dart Frog/);assert.match(await p.locator('#help-content').innerText(),/Tongues never do/);await p.locator('#help-close').click();await p.locator('#name').fill('Dart Test '+i);if(i===0){await p.locator('#create').click();await p.locator('#lobby').waitFor();}else{await p.locator('#join-code').fill(await pages[0].locator('#code').innerText());await p.locator('#join').click();await p.locator('#lobby').waitFor();}assert.equal(await p.locator('[data-arena="sunny-pond"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.arena-card').count(),4);await p.locator('#ready').click();await p.waitForFunction(()=>window.spikeDebug.lobby.players.find(p=>p.id===window.spikeDebug.playerId)?.ready);}
 pass('home, Help and four independent desktop/phone/tablet clients use Poison Tag wording and ready/join correctly');const host=pages[0],phone=pages[1];await host.locator('[data-arena="bathhouse"]').click();for(const p of pages){await p.waitForFunction(()=>window.spikeDebug.lobby.arenaId==='bathhouse'&&!window.spikeDebug.lobby.players.find(p=>p.id===window.spikeDebug.playerId).ready);await p.locator('#ready').click();await p.waitForFunction(()=>window.spikeDebug.lobby.players.find(p=>p.id===window.spikeDebug.playerId)?.ready);}await host.screenshot({path:'docs/results/bubblewash-lobby.png'});await phone.screenshot({path:'docs/results/bubblewash-lobby-mobile.png'});await host.locator('#start').click();await host.locator('#session').waitFor({state:'visible'});assert.match(await host.locator('#phase-message').innerText(),/POISON DART FROG|POISON TAG|STARTS IN/);await host.screenshot({path:'docs/results/bubblewash-reveal.png'});await host.waitForFunction(()=>window.spikeDebug.playing);await host.locator('#phase-message').filter({hasText:'POISON TAG'}).waitFor();assert.match(await host.locator('#phase-message').innerText(),/POISON TAG/);pass('public-equivalent start reaches authoritative Poison Tag; transient reveal may elapse under test load');
 for(const [i,p]of pages.entries()){const box=await p.locator('canvas').boundingBox(),stage=await p.locator('#game-stage').boundingBox();assert.ok(Math.abs(box.width/box.height-40/22.5)<.02);assert.ok(box.width>200&&box.height>100);layouts.push({config:configs[i],canvas:box,stage});}
 async function arrange(positions){const old=await host.evaluate(()=>window.spikeDebug.lastReset);await host.evaluate(positions=>window.spikeDebug.room.send('outbreak-test',{positions}),positions);await host.waitForFunction(id=>window.spikeDebug.lastReset!==id,old);}
 const start=await host.evaluate(()=>window.spikeDebug.outbreak.patientZero),other=[0,1,2,3].filter(i=>i!==start),positions=[[3,21.05],[38,21.05],[5,21.05],[35,21.05]];positions[start]=[20,20];positions[other[0]]=[20.85,20];await arrange(positions);await host.waitForFunction(i=>window.spikeDebug.outbreak.players[i].state==='transforming',other[0]);assert.match(await host.locator('#healthy-count').innerText(),/SAFE/);await phone.screenshot({path:'docs/results/bubblewash-mobile.png'});await host.waitForFunction(i=>window.spikeDebug.outbreak.players[i].state==='infectious',other[0]);pass('body-tag transformation remains authoritative with one-second grace; spots/transformation and safe-count presentation stay visible');
 const separated=[[3,21.05],[38,21.05],[5,21.05],[35,21.05]];await arrange(separated);await host.screenshot({path:'docs/results/bubblewash-game.png'});for(const p of pages)assert.ok(!(await p.locator('body').innerText()).match(/patient zero|outbreak|infect|healthy/i));await host.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).arenaId==='bathhouse');pass('Bubblewash Bathhouse + all active DOM status text uses Safe/Poison wording, with stable desktop/mobile canvas aspect ratio');
 for(let round=1;round<=4;round++){await host.waitForFunction(()=>window.spikeDebug.playing);const z=await host.evaluate(()=>window.spikeDebug.outbreak.patientZero);for(const i of [0,1,2,3].filter(i=>i!==z)){const positions=[[3,21.05],[38,21.05],[5,21.05],[35,21.05]];positions[z]=[20,20];positions[i]=[20.85,20];await arrange(positions);await host.waitForFunction(i=>window.spikeDebug.outbreak.players[i].state!=='healthy',i);}await host.locator('#results').waitFor();assert.match(await host.locator('#results-title').innerText(),/POISON TAG COMPLETE/);assert.match(await host.locator('#standings').innerText(),/Poison order/);await host.locator('#next-round').click();}
 await host.waitForFunction(()=>window.spikeDebug.outbreak.phase==='match-results');await host.locator('#results-context').filter({hasText:'Everyone was the Poison Dart Frog once'}).waitFor();assert.match(await host.locator('#results-context').innerText(),/Everyone was the Poison Dart Frog once/);assert.match(await host.locator('#standings').innerText(),/Total points/);await host.screenshot({path:'docs/results/bubblewash-results.png'});await host.locator('#return-lobby').click();await host.locator('#lobby').waitFor();await host.locator('[data-arena="canopy"]').click();await phone.waitForFunction(()=>window.spikeDebug.lobby.arenaId==='canopy');pass('complete four-round scoring/results/rotation, final standings, return/rematch and second arena selection remain functional with new language');assert.deepEqual(errors,[]);fs.writeFileSync('docs/results/bubblewash-browser.json',JSON.stringify({scope:'Local compiled server; real independent browser clients. Phone/tablet sizes are emulation, not physical iPhone/Android acceptance.',checks,layouts,errors},null,2));
}catch(e){console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}})();
