import {eligibleModifierIds,effectiveTuning,MODIFIERS,type ModifierId} from '../src/chaos/registry';
import {spawn} from 'node:child_process';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {Client,type Room} from 'colyseus.js';import type {ChaosView} from '../src/chaos/voting';import type {LobbyState,Snapshot} from '../src/network/protocol';import type {OutbreakView} from '../src/game/outbreak';
const port=3262,url=`http://127.0.0.1:${port}`,pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function until(fn:()=>unknown,label:string,ms=14000){const end=Date.now()+ms;while(!fn()){if(Date.now()>end)throw Error(label);await pause(10);}}
const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ENABLE_TESTS:'1',TEST_CHAOS_SHORT_VOTE:'1',TEST_CLASSIC_SHORT_ROUND:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1',TEST_RECONNECT_SECONDS:'1'}});let logs='';server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
const all:Peer[]=[],checks:string[]=[],metrics:Snapshot['tickMs'][]=[],activated=new Set<string>();
class Peer{client=new Client(url);room!:Room;state?:OutbreakView;c?:ChaosView;lobby?:LobbyState;s?:Snapshot;timer?:ReturnType<typeof setInterval>;seq=0;slot=-1;constructor(){all.push(this);}attach(r:Room){this.room=r;r.onMessage('welcome',x=>{this.slot=x.slot;this.seq=x.seqBase??0;});r.onMessage('lobby',x=>this.lobby=x);r.onMessage('outbreak',x=>this.state=x);r.onMessage('chaos',x=>this.c=x);r.onMessage('snapshot',x=>this.s=x);r.onMessage('notice',()=>{});r.onMessage('pong',()=>{});r.onLeave(()=>clearInterval(this.timer));r.send('hello');this.timer=setInterval(()=>{if(r.connection.isOpen&&this.slot>=0)r.send('input',{seq:++this.seq,at:Date.now(),input:{x:0,y:0,held:false}})},33);}async close(){clearInterval(this.timer);if(this.room.connection.isOpen)await this.room.leave();}}
async function scenario(mode:'poison'|'freeze'|'classic',count:number){const group=Array.from({length:count},()=>new Peer()),h=group[0];h.attach(await h.client.create('frog_party',{name:`Chaos ${mode} ${count}`}));await until(()=>h.lobby,'create');assert.equal(h.lobby!.chaosEnabled,true);for(let i=1;i<count;i++)group[i].attach(await group[i].client.joinById(h.room.roomId,{name:`Peer ${i}`}));await until(()=>group.every(p=>p.lobby?.players.length===count),'joins');group[1].room.send('select-chaos',false);await pause(30);assert.equal(h.lobby!.chaosEnabled,true);h.room.send('select-mode',mode);h.room.send('select-arena',['sunny-pond','bathhouse','canopy','toyshop'][(count-2)%4]);await until(()=>h.lobby!.mode===mode,'mode');for(const p of group)p.room.send('ready',true);await until(()=>h.lobby!.players.every(p=>p.ready),'ready');h.room.send('start');await until(()=>group.every(p=>p.state?.phase==='playing'),'start');assert.deepEqual(h.c!.active,[]);assert.deepEqual(h.s!.chaos!.active,[]);let active:string[]=[];
for(let round=1;round<=count;round++){
 await until(()=>h.state?.phase==='playing'&&h.state.round===round,'round');assert.deepEqual(h.c!.active,active);assert.deepEqual(h.s!.chaos!.active,active);h.room.send('select-chaos',false);await pause(10);assert.equal(h.lobby!.chaosEnabled,true);
 if(mode!=='classic'){const tagger=h.state!.patientZero;for(let victim=0;victim<count;victim++){if(victim===tagger)continue;const radius=effectiveTuning(active as ModifierId[]).frogRadius,y=21.5-radius;const positions=Array.from({length:count},(_,i)=>[2+4*i,18]);positions[tagger]=[20,y];positions[victim]=[20+radius*2-.03,y];h.room.send('outbreak-test',{positions});await until(()=>mode==='freeze'?h.state?.freeze?.frozen[victim]:h.state?.players[victim].infectedTick!==null,'body effect');}}
 await until(()=>h.state?.phase==='round-results',`${mode}/${count}/round ${round} results`);if(h.s)metrics.push(h.s.tickMs);h.room.send('next-round');
 if(round===count)break;await until(()=>h.c?.phase==='voting','vote open');const ballot=h.c!,old=[...active];assert.equal(ballot.choices.length,Math.min(3,eligibleModifierIds(old as ModifierId[],mode,h.lobby!.arena).length));assert.ok(ballot.choices.every(id=>!old.slice(old.length===3?1:0).includes(id)));assert.equal(ballot.expiring,old.length===3?old[0]:undefined);
 if(round===1&&count===4){const p=group[1],id=p.room.sessionId,slot=p.slot,token=p.room.reconnectionToken;p.room.send('chaos-vote',{ballotId:ballot.ballotId,id:ballot.choices[0]});await until(()=>h.c?.votes[id],'ballot saved');p.room.connection.close();await until(()=>h.lobby!.players.some(q=>q.id===id&&!q.connected),'offline');p.attach(await p.client.reconnect(token));await until(()=>p.c?.ballotId===ballot.ballotId&&p.lobby?.players.every(q=>q.connected),'reconnect');assert.equal(p.room.sessionId,id);assert.equal(p.slot,slot);assert.equal(p.c!.votes[id],ballot.choices[0]);}
 // Two equal ballots deliberately arrive in opposite order; other players abstain.
 h.room.send('chaos-vote',{ballotId:ballot.ballotId-1,id:ballot.choices[0]});h.room.send('chaos-vote',{ballotId:ballot.ballotId,id:'invalid'});
 if(round%2){group[1].room.send('chaos-vote',{ballotId:ballot.ballotId,id:ballot.priority[Math.min(1,ballot.priority.length-1)]});h.room.send('chaos-vote',{ballotId:ballot.ballotId,id:ballot.priority[0]});}
 await until(()=>h.c?.phase==='reveal','reveal');assert.equal(h.c!.winner,ballot.priority[0]);active=[...old.slice(old.length===3?1:0),h.c!.winner!];activated.add(h.c!.winner!);assert.equal(new Set(active).size,active.length);assert.deepEqual(h.c!.active,active);assert.ok(group.every(p=>p.c?.winner===h.c!.winner));await until(()=>h.state?.round===round+1&&h.state.phase==='playing'&&JSON.stringify(h.s?.chaos?.active)===JSON.stringify(active),'next');const tuning=effectiveTuning(active as ModifierId[]);assert.ok(group.every(p=>p.s?.state.frogs.every(f=>Math.abs((f.radius??.45)-tuning.frogRadius)<1e-9)));if(active.includes('tiny_trouble'))assert.equal(active.includes('mega_frogs'),false);
}
await until(()=>group.every(p=>p.state?.phase==='match-results'),'final');assert.equal(new Set(h.state!.patientZeroOrder).size,count);h.room.send('return-lobby');await until(()=>h.lobby?.phase==='lobby','lobby');assert.deepEqual(h.c?.active??[],[]);h.room.send('select-chaos',false);await until(()=>h.lobby!.chaosEnabled===false,'toggle');for(const p of group)p.room.send('ready',true);await until(()=>h.lobby!.players.every(p=>p.ready),'rematch ready');h.room.send('start');await until(()=>h.state?.phase==='playing'&&h.state.round===1,'rematch');assert.equal(h.c!.enabled,false);assert.deepEqual(h.c!.active,[]);assert.equal(h.s!.chaos,undefined);for(const p of group)await p.close();checks.push(`${mode} ${count}: default/host/lock, ${count} rounds, ${count-1} ballots, ties/abstentions, synchronized conveyor, final/rematch reset and disabled snapshots${count===4?', ballot reconnect same identity/slot':''}`);console.log(checks.at(-1));}
try{await until(()=>logs.includes('listening'),'server');await Promise.all(['poison','freeze','classic'].flatMap(mode=>[2,3,4,5,6,7,8].map(count=>scenario(mode as 'poison'|'freeze'|'classic',count))));
const g=[new Peer(),new Peer()],h=g[0];h.attach(await h.client.create('frog_party',{name:'Expiry'}));await until(()=>h.lobby,'expiry');g[1].attach(await g[1].client.joinById(h.room.roomId,{name:'Offline'}));await until(()=>h.lobby!.players.length===2,'expiry join');h.room.send('select-mode','classic');for(const p of g)p.room.send('ready',true);await until(()=>h.lobby!.players.every(p=>p.ready),'expiry ready');h.room.send('start');await until(()=>h.state?.phase==='playing','expiry start');g[1].room.connection.close();await until(()=>h.lobby?.phase==='lobby','expiry return');assert.match(h.lobby!.notice,/did not reconnect/);assert.deepEqual(h.c?.active??[],[]);checks.push('reservation expiry interrupts match and clears Chaos');
writeFileSync('docs/results/chaos-b-network.json',JSON.stringify({scope:'Compiled local server; 21 independent rooms, 2–8 clients per mode; test-only 600ms vote/150ms reveal, short countdown/Classic round; production 15s/1.5s deadlines separately unit-tested; no physical-device claim',checks,activated:[...activated],catalog:MODIFIERS.map(m=>m.id),tickMetrics:metrics},null,2));console.log('PASS',checks.length);
}finally{await Promise.allSettled(all.map(p=>p.close()));server.kill();}
