const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium'),{spawn}=require('node:child_process'),fs=require('node:fs');
(async()=>{binary.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:'3254',ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'}});let log='',browser;server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);const checks=[],errors=[],configs=[{name:'Desktop Chromium',viewport:{width:1280,height:900}},{name:'iPhone-size phone (Chromium emulation)',viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:2},{name:'Android-size phone (Chromium emulation)',viewport:{width:667,height:375},isMobile:true,hasTouch:true,deviceScaleFactor:2},{name:'Tablet (Chromium emulation)',viewport:{width:1024,height:768},isMobile:true,hasTouch:true,deviceScaleFactor:2}];
try{await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(log.includes('listening')){clearInterval(timer);resolve();}},30);setTimeout(()=>{clearInterval(timer);reject(Error(log));},10000);});browser=await chromium.launch({executablePath:await binary.executablePath(),headless:true,args:[...binary.args,'--no-sandbox','--disable-dev-shm-usage']});const pages=[];
 for(let i=0;i<configs.length;i++){const {name,...opts}=configs[i],ctx=await browser.newContext(opts),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));pages.push(p);await p.goto('http://127.0.0.1:3254/');await p.locator('#name').fill('Mobile Test '+i);if(!i){await p.locator('#create').click();await p.waitForFunction(()=>document.querySelector('#code').textContent.length===6);}else{await p.locator('#join-code').fill(await pages[0].locator('#code').textContent());await p.locator('#join').click();await p.locator('#lobby').waitFor({state:'visible'});}if(i>0)await p.locator('#ready').tap();else await p.locator('#ready').click();}
 const host=pages[0],mobile=pages[1];await host.evaluate(()=>window.spikeDebug.room.send('select-arena','canopy'));await host.waitForFunction(()=>window.spikeDebug.lobby.arenaId==='canopy');await host.evaluate(()=>window.spikeDebug.room.send('select-mode','classic'));await host.waitForFunction(()=>window.spikeDebug.lobby.mode==='classic'&&document.querySelector('#lobby-rules > summary').textContent.includes('Classic Tag'));for(const p of pages)await p.locator('#ready').click();await host.locator('#start').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.spikeDebug.playing)));checks.push('one desktop, two phones and tablet share four-player Classic Tag room; touch lobby/ready/start works');
 async function arrange(positions){const id=await mobile.evaluate(()=>window.spikeDebug.lastReset);await host.evaluate(p=>window.spikeDebug.room.send('outbreak-test',{positions:p}),positions);await mobile.waitForFunction(n=>window.spikeDebug.lastReset!==n,id);await mobile.waitForTimeout(100);}
 const ctx=mobile.context(),cdp=await ctx.newCDPSession(mobile),points=new Map();async function touch(id,target,dx=0,dy=0){const r=await mobile.locator(target).boundingBox();points.set(id,{id,x:r.x+r.width/2+dx,y:r.y+r.height/2+dy});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...points.values()]});}async function up(id){const ending=points.get(id);points.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[ending]});}
 await arrange([[29,21.05],[12,21.05],[3,21.05],[24,21.05]]);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].grounded);await mobile.locator('#touch-action').filter({hasText:'JUMP'}).waitFor();
 for(const [x,y]of [[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]]){await touch(11,'#direction-pad',x*28,y*28);await mobile.waitForFunction(d=>window.spikeDebug.input.x===d[0]&&window.spikeDebug.input.y===d[1],[x,y]);await up(11);}checks.push('actual multi-touch protocol: eight aim directions and centre/release neutral');
 await arrange([[29,21.05],[12,21.05],[3,21.05],[24,21.05]]);await touch(12,'#touch-action');await mobile.waitForTimeout(40);await up(12);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy< -7);const normal=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy);checks.push('touch quick tap sends action press/release and authoritative normal jump');
 await arrange([[29,21.05],[12,21.05],[3,21.05],[24,21.05]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.input.x===1&&window.spikeDebug.input.held&&window.spikeDebug.snapshots.at(-1).state.frogs[1].charging);await mobile.locator('#touch-action').filter({hasText:'CHARGE'}).waitFor();await mobile.waitForTimeout(1000);await up(12);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy< -15,{},{timeout:3000});const charge=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy);await up(11);checks.push('simultaneous independent thumbs maintain direction while charging; release gives stronger approved launch');
 await arrange([[29,21.05],[20,9],[3,21.05],[24,21.05]]);await touch(11,'#direction-pad',0,-28);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue?.phase==='attached'&&'terrain'in window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue.target);await mobile.waitForTimeout(150);await up(12);await mobile.waitForFunction(()=>!window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue);await up(11);checks.push('terrain tongue/active pull and release via two thumbs');
 await arrange([[20,12],[18,12],[3,21.05],[29,21.05]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue?.phase==='attached'&&window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue.target?.frog===0);await up(11);await mobile.waitForFunction(()=>{const f=window.spikeDebug.snapshots.at(-1).state.frogs;return f[0].vx<0&&f[1].vx>0;});const motion=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs.slice(0,2).map(f=>f.vx));if(!(motion[0]<0&&motion[1]>0))throw Error('reciprocal frog pull lost');await up(12);checks.push('mobile grapples desktop frog; both dynamic bodies respond and release');
 // Cancellation uses real touchCancel, not fabricated DOM events.
 await arrange([[29,21.05],[12,21.05],[3,21.05],[24,21.05]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});points.clear();await mobile.waitForFunction(()=>!window.spikeDebug.input.held&&window.spikeDebug.input.x===0);checks.push('pointer cancellation clears both inputs');
 await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.setViewportSize({width:390,height:844});points.clear();await mobile.locator('#rotate-prompt').waitFor({state:'visible'});await mobile.waitForFunction(()=>window.spikeDebug.input.x===0&&!window.spikeDebug.input.held);const identity=await mobile.evaluate(()=>window.spikeDebug.playerId);await mobile.setViewportSize({width:844,height:390});await mobile.locator('#rotate-prompt').waitFor({state:'hidden'});if(await mobile.evaluate(()=>window.spikeDebug.playerId)!==identity)throw Error('orientation identity changed');checks.push('portrait prompt, landscape return and orientation release preserve session');

 if(errors.length)throw Error(JSON.stringify(errors));fs.writeFileSync('docs/results/classic-touch.json',JSON.stringify({environment:'Local compiled server; trusted Chromium CDP simultaneous touches; emulation only, not physical iPhone or Android',configs,checks,normalJumpVelocity:normal,chargedJumpVelocity:charge,reciprocalPullVelocity:motion,errors},null,2));console.log(checks.join('\n'));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
