// Isolated local hybrid/mixed-device browser regression. No user browser automation.
const {chromium}=require('playwright-core'),bin=require('@sparticuz/chromium'),{spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{bin.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,PORT:'3188',HOST:'127.0.0.1',ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'}});let log='',browser;server.stdout.on('data',b=>log+=b);server.stderr.on('data',b=>log+=b);const errors=[],checks=[],layouts=[];
try{await new Promise((r,j)=>{let t=setInterval(()=>{if(log.includes('listening')){clearInterval(t);r();}},20);setTimeout(()=>{clearInterval(t);j(Error(log));},10000);});browser=await chromium.launch({executablePath:await bin.executablePath(),args:[...bin.args,'--no-sandbox','--disable-dev-shm-usage'],headless:true});const hybrid=await browser.newContext({hasTouch:true,viewport:{width:1024,height:768}}),p=await hybrid.newPage(),q=await browser.newPage({viewport:{width:1280,height:900}});for(const page of [p,q])page.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:3188');await q.goto('http://127.0.0.1:3188');await p.locator('#name').fill('Hybrid Host');await p.locator('#create').click();await p.waitForFunction(()=>document.querySelector('#code').textContent.length===6);await q.locator('#name').fill('Desktop Peer');await q.locator('#join-code').fill(await p.locator('#code').textContent());await q.locator('#join').click();await q.locator('#lobby').waitFor({state:'visible'});const extra=await browser.newPage();await extra.goto('http://127.0.0.1:3188');await extra.locator('#name').fill('Distant Third Frog');await extra.locator('#join-code').fill(await p.locator('#code').textContent());await extra.locator('#join').click();await extra.locator('#lobby').waitFor({state:'visible'});for(const page of [p,q,extra])await page.locator('#ready').click();await p.locator('#start').click();await p.waitForFunction(()=>window.spikeDebug.playing);const identity=await p.evaluate(()=>({id:window.spikeDebug.playerId,slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId}));const cdp=await hybrid.newCDPSession(p),touches=new Map();
async function touch(id,target,dx=0,dy=0){const b=await p.locator(target).boundingBox();touches.set(id,{id,x:b.x+b.width/2+dx,y:b.y+b.height/2+dy});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...touches.values()]});}
async function release(id){const ending=touches.get(id);if(!ending)return;touches.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[ending]});}
async function mode(enabled){const is=await p.evaluate(()=>document.body.classList.contains('touch-enabled'));if(is!==enabled){await p.locator('#touch-toggle').click();await p.waitForTimeout(150);}await p.waitForFunction(e=>document.body.classList.contains('touch-game')===e,enabled);}
async function arrange(pos){if(pos.length===2)pos.push([3,21.05]);const reset=await p.evaluate(()=>window.spikeDebug.lastReset);await p.evaluate(positions=>window.spikeDebug.room.send('outbreak-test',{positions}),pos);await p.waitForFunction(old=>window.spikeDebug.lastReset!==old,reset);await p.waitForTimeout(100);}
async function neutral(){await p.waitForFunction(()=>window.spikeDebug.input.x===0&&window.spikeDebug.input.y===0&&!window.spikeDebug.input.held);}
async function moveAfterSwitch(enabled){await mode(enabled);if(enabled){await touch(11,'#direction-pad',28);await p.waitForFunction(()=>window.spikeDebug.input.x===1);await release(11);}else{await p.keyboard.down('KeyD');await p.waitForFunction(()=>window.spikeDebug.input.x===1);await p.keyboard.up('KeyD');}await neutral();}
for(const scenario of ['grounded','airborne','charge','terrain-grapple','frog-grapple']){
 for(let cycle=0;cycle<3;cycle++){
 await arrange(scenario==='terrain-grapple'?[[16,11],[29,21.05]]:scenario==='frog-grapple'?[[12,9],[14,9]]:scenario==='airborne'?[[12,9],[29,21.05]]:[[12,21.05],[29,21.05]]);await mode(false);
 if(scenario==='charge'){await p.keyboard.down('Space');await p.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[0].charging);}
 if(scenario.includes('grapple')){await p.keyboard.down(scenario==='terrain-grapple'?'KeyW':'KeyD');await p.keyboard.down('Space');await p.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[0].tongue?.phase==='attached');}
 await p.keyboard.down('KeyD');const reset=await p.evaluate(()=>window.spikeDebug.lastReset);await mode(true);await neutral();await p.keyboard.up('Space');await p.keyboard.up('KeyW');await p.keyboard.up('KeyD');await p.waitForFunction(()=>!window.spikeDebug.snapshots.at(-1).state.frogs[0].tongue);await moveAfterSwitch(true);
 await touch(11,'#direction-pad',28);await touch(12,'#touch-action');await mode(false);await neutral();await release(11);await release(12);await moveAfterSwitch(false);await moveAfterSwitch(true);
 assert.deepEqual(await p.evaluate(()=>({id:window.spikeDebug.playerId,slot:window.spikeDebug.slot,room:window.spikeDebug.room.roomId})),identity);assert.equal(await p.evaluate(()=>window.spikeDebug.lastReset),reset);assert.equal(await p.evaluate(()=>window.spikeDebug.status),'connected');
 }checks.push(`${scenario}: 3 keyboard→touch→keyboard→touch cycles; neutral handoff, both methods recover, same player/room/reset`);
}
// Auto-repeat after a handoff cannot resurrect a keyboard key until a fresh press.
await arrange([[12,21.05],[29,21.05]]);await mode(false);await p.keyboard.down('KeyD');await mode(true);await p.keyboard.down('KeyD');await neutral();await p.keyboard.up('KeyD');await moveAfterSwitch(false);checks.push('held-key auto-repeat after handoff cannot resurrect stale direction');
for(const viewport of [{width:1366,height:768},{width:1024,height:768},{width:844,height:390},{width:667,height:375},{width:568,height:320}]){await p.setViewportSize(viewport);for(const enabled of [false,true]){await mode(enabled);await p.waitForTimeout(200);const c=await p.locator('canvas').boundingBox(),g=await p.locator('#game').boundingBox(),footer=await p.locator('#session-footer').boundingBox();assert.ok(c.width>200&&c.height>100);assert.ok(Math.abs(c.width/c.height-32/18)<.03);assert.ok(c.y+c.height<=viewport.height+1);assert.ok(footer.y+footer.height<=viewport.height+1);assert.ok(Math.abs(c.width-g.width)<3||Math.abs(c.height-g.height)<3,'FIT must fill one available dimension');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);layouts.push({viewport,touch:enabled,canvas:c,available:g,footer});}}
checks.push('5 landscape sizes × both input layouts: aspect ratio, FIT maximum dimension, footer and arena in viewport, no horizontal overflow');
await p.setViewportSize({width:844,height:390});await mode(true);if(await p.locator('#fullscreen').isVisible()){await p.locator('#fullscreen').click();await p.waitForFunction(()=>!!document.fullscreenElement);await p.locator('#fullscreen').filter({hasText:'Exit Fullscreen'}).waitFor();await p.locator('#fullscreen').click();await p.waitForFunction(()=>!document.fullscreenElement);checks.push('user gesture Fullscreen API enter/exit and label/resize work in headless Chromium');}
await p.setViewportSize({width:390,height:844});await p.locator('#rotate-prompt').waitFor({state:'visible'});await neutral();await p.setViewportSize({width:844,height:390});await p.locator('#rotate-prompt').waitFor({state:'hidden'});await moveAfterSwitch(true);checks.push('portrait/landscape preserves identity and restores controls');
await p.reload();await p.waitForFunction(id=>window.spikeDebug.playerId===id&&window.spikeDebug.playing,identity.id);await moveAfterSwitch(false);await moveAfterSwitch(true);checks.push('reload reconnect after repeated switching restores same frog and both input methods');
await p.screenshot({path:'docs/results/compat-6.png'});const zero=await p.evaluate(()=>window.spikeDebug.outbreak.patientZero);await arrange([[16,9],[15.12,9],[16.88,9]]);await p.locator('#results').waitFor({state:'visible'});const r=await p.evaluate(()=>window.spikeDebug.outbreak);assert.equal(r.players[zero].roundPoints,0);for(const slot of r.roundWinners)assert.equal(r.players[slot].placementBonus,2);for(const record of r.players)assert.equal(Math.round(record.roundPoints*10),Math.round((record.survivalPoints+record.placementBonus)*10));assert.ok((await p.locator('#standings').textContent()).includes('Survival'));assert.ok((await p.locator('#standings').textContent()).includes('Bonus'));checks.push('authoritative survival score + 2 bonus displayed as separate round-results components');
// Unsupported and rejected fullscreen are explicit local capability fault tests.
const unsupported=await browser.newPage();await unsupported.addInitScript(()=>Object.defineProperty(document,'fullscreenEnabled',{get:()=>false}));await unsupported.goto('http://127.0.0.1:3188');assert.equal(await unsupported.locator('#fullscreen').isVisible(),false);const rejected=await browser.newPage();await rejected.addInitScript(()=>{Object.defineProperty(document,'fullscreenEnabled',{get:()=>true});Element.prototype.requestFullscreen=()=>Promise.reject(new Error('restricted'));});await rejected.goto('http://127.0.0.1:3188');await rejected.locator('#fullscreen').click();await rejected.locator('#notice').filter({hasText:'continue playing normally'}).waitFor();checks.push('fullscreen absent/restricted: hidden unsupported button or readable failure, ordinary play unaffected');
assert.deepEqual(errors,[]);fs.writeFileSync('docs/results/compat-milestone-6.json',JSON.stringify({environment:'Local authoritative server; Chromium trusted touch and keyboard, hybrid + desktop; capability fault injection only in isolated tests; not physical acceptance',checks,layouts,round:r,errors},null,2));console.log(JSON.stringify({checks,errors,layouts}));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
