import {spawn} from 'node:child_process';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {Client,type Room} from 'colyseus.js';import type {LobbyState,Snapshot} from '../src/network/protocol';import type {OutbreakView} from '../src/game/outbreak';
const port=3192,url=`http://127.0.0.1:${port}`,wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function until(fn:()=>unknown,label:string){const end=Date.now()+15000;while(!fn()){if(Date.now()>end)throw Error(label);await wait(15);}}
const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'}});let log='';server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);const checks:string[]=[],peers:Peer[]=[];function pass(s:string){checks.push(s);console.log('PASS '+s);}
class Peer{client=new Client(url);room!:Room;lobby?:LobbyState;state?:OutbreakView;last?:Snapshot;notice='';slot=-1;seq=0;timer?:ReturnType<typeof setInterval>;constructor(){peers.push(this);}attach(r:Room){this.room=r;this.seq=0;r.onMessage('welcome',x=>{this.slot=x.slot;this.seq=Math.max(this.seq,x.seqBase??0);});r.onMessage('lobby',(x:LobbyState)=>this.lobby=x);r.onMessage('outbreak',(x:OutbreakView)=>this.state=x);r.onMessage('snapshot',(x:Snapshot)=>this.last=x);r.onMessage('notice',x=>this.notice=x);r.onMessage('pong',()=>{});r.onLeave(()=>clearInterval(this.timer));r.send('hello');this.timer=setInterval(()=>{if(this.slot>=0&&r.connection.isOpen)r.send('input',{seq:++this.seq,at:Date.now(),input:{x:0,y:0,held:false}});},33);}async leave(){clearInterval(this.timer);if(this.room.connection.isOpen)await this.room.leave();}}
try{await until(()=>log.includes('listening'),'startup');for(const arenaId of ['canopy','swingworks','sunny-pond','toyshop']as const)for(const count of [2,3,4,8]){const group=Array.from({length:count},()=>new Peer()),host=group[0];host.attach(await host.client.create('frog_party',{name:'Arena Host'}));await until(()=>host.lobby,'create');for(const [i,p]of group.entries())if(i)p.attach(await p.client.joinById(host.room.roomId,{name:`Peer ${i}`}));await until(()=>group.every(p=>p.lobby?.players.length===count),'join');assert.equal(host.lobby!.arenaId,'canopy');group[1].room.send('select-arena','swingworks');await until(()=>group[1].notice.includes('host'),'nonhost arena');assert.equal(host.lobby!.arenaId,'canopy');host.room.send('select-arena','bad');await until(()=>host.notice.includes('valid'),'invalid arena');for(const p of group)p.room.send('ready',true);await until(()=>host.lobby!.players.every(p=>p.ready),'ready');host.room.send('select-arena','swingworks');await until(()=>group.every(p=>p.lobby?.arenaId==='swingworks'),'sync choice');assert.ok(host.lobby!.players.every(p=>!p.ready));host.room.send('start');await until(()=>host.notice.includes('ready'),'readiness reset blocks start');host.room.send('select-arena',arenaId);await until(()=>host.lobby!.arenaId===arenaId,'requested arena');for(const p of group)p.room.send('ready',true);await until(()=>host.lobby!.players.every(p=>p.ready),'all ready');host.room.send('start');await until(()=>group.every(p=>p.state?.phase==='playing'&&p.last?.arenaId===arenaId),'arena gameplay');const order=[...host.state!.patientZeroOrder];assert.equal(new Set(order).size,count);host.notice='';host.room.send('select-arena',arenaId==='canopy'?'swingworks':'canopy');await until(()=>host.notice.includes('lobby'),'frozen map');assert.equal(host.lobby!.arenaId,arenaId);
 // Real reconnect keeps slot, room and authoritative map, including the predictor's required snapshot id.
 const p=group[1],token=p.room.reconnectionToken,slot=p.slot,id=p.room.sessionId;clearInterval(p.timer);p.room.connection.close();await until(()=>host.lobby!.players.some(x=>x.id===id&&!x.connected),'offline');p.attach(await p.client.reconnect(token));await until(()=>p.last?.arenaId===arenaId&&p.slot===slot&&host.lobby!.players.every(x=>x.connected),'reconnect map');assert.equal(p.room.sessionId,id);
 for(let round=1;round<=count;round++){await until(()=>host.state?.phase==='playing'&&host.state.round===round,'round start');assert.equal(host.state!.patientZero,order[round-1]);const zero=host.state!.patientZero;for(let victim=0;victim<count;victim++){if(victim===zero)continue;const reset=host.last!.resetId;const positions=Array.from({length:count},(_,i)=>[2+36*i/(count-1),21.05]);positions[zero]=[20,10];positions[victim]=[20.88,10];host.room.send('outbreak-test',{positions});await until(()=>host.last!.resetId!==reset&&host.state!.players[victim].roundPoints!==null,'body-contact victim infection');}await until(()=>host.state?.phase==='round-results','all infected ends round');assert.equal(host.state!.players[zero].roundPoints,0);for(const record of host.state!.players){assert.equal(Math.round(record.roundPoints!*10),Math.round((record.survivalPoints+record.placementBonus)*10));}assert.equal(host.lobby!.arenaId,arenaId);host.room.send('next-round');}
 await until(()=>group.every(p=>p.state?.phase==='match-results'),'final standings');host.room.send('return-lobby');await until(()=>group.every(p=>p.lobby?.phase==='lobby'),'rematch lobby');assert.equal(host.lobby!.arenaId,arenaId);assert.ok(host.lobby!.players.every(p=>!p.ready));for(const p of group)await p.leave();pass(`${arenaId}: ${count} clients; synchronized host choice, invalid/nonhost rejection, Ready reset, frozen map, same-slot reconnect, ${count} rounds/rotation/survival scoring/final/rematch`);}
 // Independent simultaneous rooms cannot overwrite one another's map.
 const a=new Peer(),b=new Peer();a.attach(await a.client.create('frog_party',{name:'Room A'}));b.attach(await b.client.create('frog_party',{name:'Room B'}));await until(()=>a.lobby&&b.lobby,'rooms');a.room.send('select-arena','swingworks');await until(()=>a.lobby!.arenaId==='swingworks','one room change');assert.equal(b.lobby!.arenaId,'canopy');await a.leave();await b.leave();pass('independent room selections are isolated');writeFileSync('docs/results/milestone-14-arenas.json',JSON.stringify({environment:'Local compiled server; independent real WebSocket clients; short test countdown; unchanged production grace/scoring',checks},null,2));
}finally{for(const p of peers)clearInterval(p.timer);server.kill();}
