import {spawn} from 'node:child_process';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {Client,type Room} from 'colyseus.js';import type {LobbyState,Snapshot} from '../src/network/protocol';import type {OutbreakView} from '../src/game/outbreak';
const port=3253,url=`http://127.0.0.1:${port}`,wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function until(fn:()=>unknown,label:string){const end=Date.now()+15000;while(!fn()){if(Date.now()>end)throw Error(label);await wait(15);}}
const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'}});let log='';server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);const checks:string[]=[],peers:Peer[]=[];function pass(s:string){checks.push(s);console.log('PASS '+s);}
class Peer{client=new Client(url);room!:Room;lobby?:LobbyState;state?:OutbreakView;last?:Snapshot;notice='';slot=-1;seq=0;input={x:0,y:0,held:false};timer?:ReturnType<typeof setInterval>;constructor(){peers.push(this);}attach(r:Room){this.room=r;this.seq=0;r.onMessage('welcome',x=>{this.slot=x.slot;this.seq=Math.max(this.seq,x.seqBase??0);});r.onMessage('lobby',(x:LobbyState)=>this.lobby=x);r.onMessage('outbreak',(x:OutbreakView)=>this.state=x);r.onMessage('snapshot',(x:Snapshot)=>this.last=x);r.onMessage('notice',x=>this.notice=x);r.onMessage('pong',()=>{});r.onLeave(()=>clearInterval(this.timer));r.send('hello');this.timer=setInterval(()=>{if(this.slot>=0&&r.connection.isOpen)r.send('input',{seq:++this.seq,at:Date.now(),input:this.input});},33);}async leave(){clearInterval(this.timer);if(this.room.connection.isOpen)await this.room.leave();}}
try{await until(()=>log.includes('listening'),'startup');for(const count of [2,4,8]){const group=Array.from({length:count},()=>new Peer()),host=group[0];host.attach(await host.client.create('frog_party',{name:'Pond Host'}));await until(()=>host.lobby,'create');for(const[i,p]of group.entries())if(i)p.attach(await p.client.joinById(host.room.roomId,{name:`Pond ${i}`}));await until(()=>host.lobby!.players.length===count,'join');host.room.send('select-arena','sunny-pond');await until(()=>host.lobby?.arenaId==='sunny-pond','selection');for(const p of group)p.room.send('ready',true);await until(()=>host.lobby!.players.every(p=>p.ready),'ready');host.room.send('start');await until(()=>group.every(p=>p.state?.phase==='playing'&&p.last?.arenaId==='sunny-pond'),'playing');
async function arrange(positions:number[][],velocities?:number[][]){const reset=host.last!.resetId;host.room.send('outbreak-test',{positions,velocities});await until(()=>host.last!.resetId!==reset,'arrange');}
const base=()=>Array.from({length:count},(_,i)=>[2+36*i/(count-1),21.05]);let pos=base();pos[0]=[13,14.8];if(count>2)pos[1]=[27,14.8];await arrange(pos,Array.from({length:count},(_,i)=>[0,i===0||i===1&&count>2?3:0]));await until(()=>host.last!.state.frogs[0].surfaceBounceTick!==undefined,'server bounce');assert.ok(host.last!.state.frogs[0].vy<0);if(count>2)await until(()=>host.last!.state.frogs[1].surfaceBounceTick!==undefined,'simultaneous pad');const event=host.last!.state.frogs[0].surfaceBounceTick;await until(()=>group.every(p=>p.last?.state.frogs[0].surfaceBounceTick===event),'all clients saw bounce');
await until(()=>host.last!.state.frogs[0].surfaceBounceTick!>event!,'hands-off repeat bounce');
pos=base();pos[0]=[5,17.2];await arrange(pos);await until(()=>host.last!.state.frogs[0].stickyMud,'mud contact');host.input={x:1,y:0,held:false};await until(()=>Math.abs(host.last!.state.frogs[0].vx-4.5)<.15,'server mud speed');host.input={x:0,y:0,held:false};pos=base();pos[0]=[14,19];await arrange(pos);await until(()=>!host.last!.state.frogs[0].stickyMud,'mud clear');
pos=base();pos[0]=[20,14];await arrange(pos);host.input={x:0,y:-1,held:true};await until(()=>host.last!.state.frogs[0].tongue?.phase==='attached','terrain tongue');assert.ok(host.last!.state.frogs[0].tongue?.target&&'terrain'in host.last!.state.frogs[0].tongue!.target!);host.input={x:0,y:0,held:false};await until(()=>!host.last!.state.frogs[0].tongue,'release');assert.ok(host.last!.state.frogs.every(f=>Number.isFinite(f.x+f.y+f.vx+f.vy)));for(const p of group)await p.leave();pass(`${count} clients: authoritative pond selection, body-land bounce/event sync, simultaneous pads, 4.5 mud speed/immediate clear, terrain grapple/release, finite movement`);}
writeFileSync('docs/results/milestone-13-refinement-surfaces.json',JSON.stringify({environment:'Independent loopback authoritative WebSocket clients; test-only positions and short countdown; production surface tuning',checks},null,2));}finally{for(const p of peers)clearInterval(p.timer);server.kill();}
