const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium'),{spawn}=require('node:child_process'),fs=require('node:fs');
(async()=>{binary.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:'3177',ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'}});let log='',browser;server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);const checks=[],errors=[],configs=[{name:'Desktop Chromium',viewport:{width:1280,height:900}},{name:'iPhone-size phone (Chromium emulation)',viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:2},{name:'Android-size phone (Chromium emulation)',viewport:{width:667,height:375},isMobile:true,hasTouch:true,deviceScaleFactor:2},{name:'Tablet (Chromium emulation)',viewport:{width:1024,height:768},isMobile:true,hasTouch:true,deviceScaleFactor:2}];
try{await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(log.includes('listening')){clearInterval(timer);resolve();}},30);setTimeout(()=>{clearInterval(timer);reject(Error(log));},10000);});browser=await chromium.launch({executablePath:await binary.executablePath(),headless:true,args:[...binary.args,'--no-sandbox','--disable-dev-shm-usage']});const pages=[];
 for(let i=0;i<configs.length;i++){const {name,...opts}=configs[i],ctx=await browser.newContext(opts),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));pages.push(p);await p.goto('http://127.0.0.1:3177/');await p.locator('#name').fill('Mobile Test '+i);if(!i){await p.locator('#create').click();await p.waitForFunction(()=>document.querySelector('#code').textContent.length===6);}else{await p.locator('#join-code').fill(await pages[0].locator('#code').textContent());await p.locator('#join').click();await p.locator('#lobby').waitFor({state:'visible'});}if(i>0)await p.locator('#ready').tap();else await p.locator('#ready').click();}
 const host=pages[0],mobile=pages[1];await host.locator('#start').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>window.spikeDebug.playing)));checks.push('one desktop, two phones and tablet share four-player room; touch lobby/ready/start works');
 async function arrange(positions){const id=await mobile.evaluate(()=>window.spikeDebug.lastReset);await host.evaluate(p=>window.spikeDebug.room.send('outbreak-test',{positions:p}),positions);await mobile.waitForFunction(n=>window.spikeDebug.lastReset!==n,id);await mobile.waitForTimeout(100);}
 const ctx=mobile.context(),cdp=await ctx.newCDPSession(mobile),points=new Map();async function touch(id,target,dx=0,dy=0){const r=await mobile.locator(target).boundingBox();points.set(id,{id,x:r.x+r.width/2+dx,y:r.y+r.height/2+dy});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...points.values()]});}async function up(id){const ending=points.get(id);points.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[ending]});}
 await arrange([[29,16.55],[12,16.55],[3,16.55],[24,16.55]]);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].grounded);await mobile.locator('#touch-action').filter({hasText:'JUMP'}).waitFor();
 for(const [x,y]of [[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]]){await touch(11,'#direction-pad',x*28,y*28);await mobile.waitForFunction(d=>window.spikeDebug.input.x===d[0]&&window.spikeDebug.input.y===d[1],[x,y]);await up(11);}checks.push('actual multi-touch protocol: eight aim directions and centre/release neutral');
 await arrange([[29,16.55],[12,16.55],[3,16.55],[24,16.55]]);await touch(12,'#touch-action');await mobile.waitForTimeout(40);await up(12);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy< -7);const normal=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy);checks.push('touch quick tap sends action press/release and authoritative normal jump');
 await arrange([[29,16.55],[12,16.55],[3,16.55],[24,16.55]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.input.x===1&&window.spikeDebug.input.held&&window.spikeDebug.snapshots.at(-1).state.frogs[1].charging);await mobile.locator('#touch-action').filter({hasText:'CHARGE'}).waitFor();await mobile.waitForTimeout(1000);await up(12);await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy< -15,{},{timeout:3000});const charge=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].vy);await up(11);checks.push('simultaneous independent thumbs maintain direction while charging; release gives stronger approved launch');
 await arrange([[29,16.55],[16,11],[3,16.55],[24,16.55]]);await touch(11,'#direction-pad',0,-28);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue?.phase==='attached'&&'terrain'in window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue.target);await mobile.waitForTimeout(150);await up(12);await mobile.waitForFunction(()=>!window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue);await up(11);checks.push('terrain tongue/active pull and release via two thumbs');
 await arrange([[14,9],[12,9],[3,16.55],[29,16.55]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.waitForFunction(()=>window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue?.phase==='attached'&&window.spikeDebug.snapshots.at(-1).state.frogs[1].tongue.target?.frog===0);await up(11);await mobile.waitForFunction(()=>{const f=window.spikeDebug.snapshots.at(-1).state.frogs;return f[0].vx<0&&f[1].vx>0;});const motion=await mobile.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs.slice(0,2).map(f=>f.vx));if(!(motion[0]<0&&motion[1]>0))throw Error('reciprocal frog pull lost');await up(12);checks.push('mobile grapples desktop frog; both dynamic bodies respond and release');
 // Cancellation uses real touchCancel, not fabricated DOM events.
 await arrange([[29,16.55],[12,16.55],[3,16.55],[24,16.55]]);await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});points.clear();await mobile.waitForFunction(()=>!window.spikeDebug.input.held&&window.spikeDebug.input.x===0);checks.push('pointer cancellation clears both inputs');
 await touch(11,'#direction-pad',28,0);await touch(12,'#touch-action');await mobile.setViewportSize({width:390,height:844});points.clear();await mobile.locator('#rotate-prompt').waitFor({state:'visible'});await mobile.waitForFunction(()=>window.spikeDebug.input.x===0&&!window.spikeDebug.input.held);const identity=await mobile.evaluate(()=>window.spikeDebug.playerId);await mobile.setViewportSize({width:844,height:390});await mobile.locator('#rotate-prompt').waitFor({state:'hidden'});if(await mobile.evaluate(()=>window.spikeDebug.playerId)!==identity)throw Error('orientation identity changed');checks.push('portrait prompt, landscape return and orientation release preserve session');
 // Verify the visible arena is disjoint from comfortable control targets.
 const layouts=[];for(let i=1;i<pages.length;i++){const p=pages[i],canvas=await p.locator('canvas').boundingBox(),pad=await p.locator('#direction-pad').boundingBox(),action=await p.locator('#touch-action').boundingBox();if(pad.width<80||action.width<80||canvas.x<pad.x+pad.width||canvas.x+canvas.width>action.x||canvas.y+canvas.height>configs[i].viewport.height){await p.screenshot({path:'/tmp/frog-mobile-layout.png'});throw Error('touch targets obscure arena or exceed viewport '+JSON.stringify({config:configs[i],canvas,pad,action}));}const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('horizontal mobile overflow');layouts.push({device:configs[i].name,canvas,pad,action});}await mobile.screenshot({path:'docs/results/mobile-5-1-landscape.png'});checks.push('phone/tablet arena fully visible, controls >=80px, no canvas overlap or horizontal overflow');
 const second=pages[2];await second.setViewportSize({width:375,height:667});await second.locator('#rotate-prompt').waitFor({state:'visible'});await second.screenshot({path:'docs/results/mobile-5-1-portrait.png'});await second.setViewportSize({width:667,height:375});
 await mobile.setViewportSize({width:568,height:320});await mobile.waitForTimeout(150);const smallCanvas=await mobile.locator('canvas').boundingBox(),leaveBox=await mobile.locator('#leave').boundingBox();if(smallCanvas.y+smallCanvas.height>320||leaveBox.y+leaveBox.height>320)throw Error('small landscape phone cuts off controls/footer');await mobile.setViewportSize({width:844,height:390});checks.push('568x320 landscape compatibility and visible footer');
 // Reload a mobile player during active Outbreak, keeping the same token/identity.
 await mobile.reload();await mobile.waitForFunction(id=>window.spikeDebug.status==='connected'&&window.spikeDebug.playerId===id,identity);await mobile.waitForFunction(()=>window.spikeDebug.playing);checks.push('mobile page reload reconnect restores identity/slot during Outbreak');const download=mobile.waitForEvent('download');await mobile.locator('#mobile-export').tap();const data=JSON.parse(fs.readFileSync(await (await download).path(),'utf8'));if(data.milestone!==5.1||!data.touch.enabled||'token'in data)throw Error('mobile diagnostics invalid');checks.push('mobile Diagnostics button exports touch/viewport/network state without reconnect token');
 // Four production rule rounds with short test intros, actual body contact and mobile results navigation.
 for(let round=1;round<=4;round++){await host.waitForFunction(r=>window.spikeDebug.playing&&window.spikeDebug.outbreak.round===r,round);const zero=await host.evaluate(()=>window.spikeDebug.outbreak.patientZero);const pos=Array.from({length:4},(_,i)=>[16+(i===zero?0:(i<zero?-.88:.88)),9]);await arrange(pos);await host.locator('#results').waitFor({state:'visible'});await Promise.all(pages.slice(1).map(p=>p.locator('#results').waitFor({state:'visible'})));for(const p of pages.slice(1)){if(await p.locator('#rotate-prompt').isVisible())throw Error('portrait prompt obstructs results');if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('results overflow');}await host.locator('#next-round').click();}
 await mobile.locator('#results-title').filter({hasText:'MATCH COMPLETE'}).waitFor({state:'visible'});await mobile.screenshot({path:'docs/results/mobile-5-1-results.png'});checks.push('mixed-device complete Outbreak, round/final standings and no inaccessible results');await host.locator('#return-lobby').click();await Promise.all(pages.map(p=>p.locator('#lobby').waitFor({state:'visible'})));checks.push('return/rematch lobby remains touch usable');
 for(const p of pages)await p.locator('#leave').click();const phoneHost=pages[1],phonePeer=pages[2];await phoneHost.locator('#create').tap();await phoneHost.locator('#lobby').waitFor({state:'visible'});await phonePeer.locator('#join-code').fill(await phoneHost.locator('#code').textContent());await phonePeer.locator('#join').tap();await phonePeer.locator('#lobby').waitFor({state:'visible'});for(const p of [phoneHost,phonePeer])await p.locator('#ready').tap();await phoneHost.locator('#start').tap();for(let r=1;r<=2;r++){await phoneHost.waitForFunction(n=>window.spikeDebug.playing&&window.spikeDebug.outbreak.round===n,r);await phoneHost.evaluate(()=>window.spikeDebug.room.send('outbreak-test',{positions:[[16,9],[16.88,9]]}));await phoneHost.locator('#results').waitFor({state:'visible'});await phoneHost.locator('#next-round').tap();}await phoneHost.locator('#results-title').filter({hasText:'MATCH COMPLETE'}).waitFor({state:'visible'});await phoneHost.locator('#return-lobby').tap();await phoneHost.locator('#lobby').waitFor({state:'visible'});checks.push('phone-only two-client room, touch host Start/Next/Final/Return and full match');
 if(errors.length)throw Error(JSON.stringify(errors));const report={environment:'Local compiled authoritative server; trusted CDP multi-touch input in isolated Chromium contexts (not physical iOS/Safari/Android devices); test-only body arrangements and 6/12-tick intros; unchanged 60-tick grace',configs,checks,normalJumpVelocity:normal,chargedJumpVelocity:charge,reciprocalPullVelocity:motion,layouts,errors};fs.writeFileSync('docs/results/mobile-milestone-5-1.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
