import {spawn} from 'node:child_process';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {Client,type Room} from 'colyseus.js';import type {OutbreakView} from '../src/game/outbreak';import type {LobbyState,Snapshot} from '../src/network/protocol';
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(condition:()=>unknown,label:string,timeout=5000){const end=Date.now()+timeout;while(!condition()){if(Date.now()>end)throw Error(`Timeout: ${label}`);await wait(10);}}
const port=2977,url=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['--import','tsx','server/index.ts'],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),ENABLE_TESTS:'1',TEST_OUTBREAK_SHORT_COUNTDOWN:'1'},stdio:['ignore','pipe','pipe']});server.stderr.on('data',x=>process.stderr.write(x));
const peers:Peer[]=[],checks:string[]=[],matches:unknown[]=[];const pass=(name:string)=>{checks.push(name);console.log(`PASS ${name}`);};
class Peer{
 client=new Client(url);room!:Room;rules?:OutbreakView;lobby?:LobbyState;last?:Snapshot;slot=-1;seq=0;notice='';firstPlayingTicks=new Map<number,number>();timer?:ReturnType<typeof setInterval>;input={x:0,y:0,held:false};
 constructor(){peers.push(this);}
 attach(room:Room){this.room=room;this.slot=-1;this.seq=0;room.onMessage('welcome',x=>{this.slot=x.slot;this.seq=Math.max(this.seq,x.seqBase??0);});room.onMessage('outbreak',(state:OutbreakView|null)=>{this.rules=state??undefined;if(state?.phase==='playing'&&!this.firstPlayingTicks.has(state.round))this.firstPlayingTicks.set(state.round,state.tick);});room.onMessage('snapshot',(s:Snapshot)=>this.last=s);room.onMessage('lobby',(s:LobbyState)=>this.lobby=s);room.onMessage('notice',(s:string)=>this.notice=s);room.onMessage('pong',()=>{});room.onError(()=>{});room.onLeave(()=>clearInterval(this.timer));room.send('hello');clearInterval(this.timer);this.timer=setInterval(()=>this.send(),33);}
 send(){if(this.lobby?.phase==='game'&&this.slot>=0&&this.room.connection.isOpen)this.room.send('input',{seq:++this.seq,at:Date.now(),input:this.input});}
 async create(name:string){this.attach(await this.client.create('frog_party',{name}));await until(()=>this.lobby,'create');}
 async join(host:Peer,name:string){this.attach(await this.client.joinById(host.room.roomId,{name}));await until(()=>this.lobby,'join');}
 async drop(){clearInterval(this.timer);this.room.connection.close();await wait(80);}
 async leave(){clearInterval(this.timer);if(this.room?.connection.isOpen)await this.room.leave();}
}
function away(count:number){return Array.from({length:count},(_,i)=>[2+28*i/(count-1),16]);}
async function arrange(host:Peer,positions:number[][]){const before=host.last?.resetId;host.room.send('outbreak-test',{positions});await until(()=>host.last?.resetId!==before,'arranged authoritative bodies');}
async function game(group:Peer[]){for(const p of group)p.room.send('ready',true);await until(()=>group[0].lobby!.players.every(p=>p.ready),'ready');group[0].room.send('start');await until(()=>group.every(p=>p.rules?.phase==='playing'),'round starts');}
try{
 await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server startup timeout')),10000);server.stdout.on('data',x=>{if(String(x).includes('listening')){clearTimeout(timer);resolve();}});server.once('exit',c=>reject(Error(`server exited ${c}`)));});
 for(const count of [2,3,4,8]){
  const group=Array.from({length:count},()=>new Peer()),host=group[0];await host.create(`Host ${count}`);await Promise.all(group.slice(1).map((p,i)=>p.join(host,`Frog ${i+2}`)));await until(()=>host.lobby!.players.length===count,'roster');await game(group);const order=[...host.rules!.patientZeroOrder],seen:number[]=[];const rounds:unknown[]=[];
  for(let round=1;round<=count;round++){
   await until(()=>host.rules?.phase==='playing'&&host.rules.round===round,`round ${round}`);const zero=host.rules!.patientZero;seen.push(zero);assert.equal(host.rules!.players[zero].state,'infectious');assert.equal(host.rules!.players[zero].roundPoints,0);assert.equal(new Set(host.rules!.patientZeroOrder).size,count);
   // Force real Planck body contact in an isolated test server. Production has no arrangement handler.
   const others=Array.from({length:count},(_,i)=>i).filter(i=>i!==zero);let infected=1;
   if(count===4&&round===1){
    let pos=away(count);pos[zero]=[16,9];pos[others[0]]=[15.12,9];pos[others[1]]=[16.88,9];pos[others[2]]=[3,16];await arrange(host,pos);await until(()=>host.rules!.players[others[0]].roundPoints!==null&&host.rules!.players[others[1]].roundPoints!==null,'simultaneous body infection');const a=host.rules!.players[others[0]],b=host.rules!.players[others[1]];assert.equal(a.infectedTick,b.infectedTick);assert.equal(a.infectionPlace,b.infectionPlace);assert.equal(a.roundPoints,1);assert.equal(b.roundPoints,1);infected=3;pass('four-player physical same-tick infections receive equal placement and score');
    pos=away(count);pos[zero]=[3,16];pos[others[0]]=[16,16.55];pos[others[1]]=[29,16];pos[others[2]]=[16.88,16.55];await arrange(host,pos);await wait(250);assert.equal(host.rules!.players[others[2]].state,'healthy');await until(()=>host.rules!.players[others[2]].roundPoints===3,'grace expires during ongoing body contact',1800);assert.equal(host.rules!.players[others[2]].infectedTick!-a.infectedTick!,60);pass('real body contact cannot chain during grace; ongoing contact infects at 60 ticks');
   }else{
    for(const target of others){let pos=away(count);pos[zero]=[16,9];pos[target]=[16.88,9];for(const i of others)if(i!==target)pos[i]=[2+28*i/(count-1),16];await arrange(host,pos);await until(()=>host.rules!.players[target].roundPoints!==null,'body infection');assert.equal(host.rules!.players[target].roundPoints,infected++);}
   }
   await until(()=>host.rules!.phase==='round-results','round completed');assert.equal(host.rules!.players.filter(p=>p.state!=='healthy').length,count);assert.ok(host.rules!.roundWinners.length);const elapsed=host.rules!.elapsedMs;await wait(80);assert.equal(host.rules!.elapsedMs,elapsed);assert.ok(group.every(p=>p.rules!.phase==='round-results'));assert.ok(group.every(p=>p.firstPlayingTicks.get(round)===host.firstPlayingTicks.get(round)));rounds.push({round,patientZero:zero,points:host.rules!.players.map(p=>p.roundPoints),winners:host.rules!.roundWinners,elapsedMs:elapsed});
   const nonhost=group[1];nonhost.room.send('next-round');await until(()=>nonhost.notice.includes('host'),'nonhost continuation denied');assert.equal(host.rules!.phase,'round-results');host.room.send('next-round');
  }
  await until(()=>host.rules!.phase==='match-results','final standings');assert.deepEqual(seen,order);const total=host.rules!.players.map(p=>p.totalPoints);const calculated=Array(count).fill(0);for(const r of rounds as {points:number[]}[])r.points.forEach((p,i)=>calculated[i]+=p);assert.deepEqual(total,calculated);if(count===2){assert.deepEqual(total,[1,1]);assert.deepEqual(host.rules!.matchWinners,[0,1]);pass('two-player full match ends with a shared victory and no tiebreak');}
  host.room.send('return-lobby');await until(()=>host.lobby?.phase==='lobby'&&!host.rules,'return lobby');assert.ok(host.lobby!.players.every(p=>!p.ready));await game(group);assert.ok(host.rules!.players.every(p=>p.totalPoints===0));pass(`${count}-client complete match: rotation, timer, scoring, round/final results, return and fresh rematch`);matches.push({clients:count,patientZeroOrder:order,rounds,totalPoints:total});await Promise.all(group.map(p=>p.leave()));
 }
 // A disconnected, healthy roster member remains infectable; reconnection preserves rules as well as body identity.
 const group=Array.from({length:3},()=>new Peer()),host=group[0];await host.create('Reconnect Host');await Promise.all(group.slice(1).map((p,i)=>p.join(host,`Reconnect ${i+2}`)));await game(group);const zero=host.rules!.patientZero,target=[1,2].find(i=>i!==zero)!,victim=group.find(p=>p.slot===target)!;const shooter=group.find(p=>p.slot===zero)!;const tonguePositions=away(3);tonguePositions[zero]=[12,9];tonguePositions[target]=[14,9];await arrange(host,tonguePositions);await wait(100);shooter.input={x:1,y:0,held:true};shooter.send();await until(()=>host.last?.state.frogs[zero].tongue?.phase==='attached','frog tongue attached');assert.equal(host.rules!.players[target].state,'healthy');assert.equal(host.rules!.players[target].roundPoints,null);shooter.input={x:0,y:0,held:false};shooter.send();await until(()=>!host.last?.state.frogs[zero].tongue,'tongue released');pass('authoritative frog-to-frog tongue attachment and release do not directly infect');const id=victim.room.sessionId,token=victim.room.reconnectionToken;await victim.drop();await until(()=>host.lobby!.players[target].connected===false,'offline');const positions=away(3);positions[zero]=[16,9];positions[target]=[16.88,9];const other=[0,1,2].find(i=>i!==zero&&i!==target)!;positions[other]=[3,16];await arrange(host,positions);await until(()=>host.rules!.players[target].roundPoints===1,'offline infection');assert.equal(host.rules!.phase,'playing');victim.attach(await victim.client.reconnect(token));await until(()=>victim.rules&&victim.slot===target&&host.lobby!.players[target].connected,'reconnect');assert.equal(victim.room.sessionId,id);assert.equal(victim.rules!.players[target].roundPoints,1);assert.equal(victim.last!.state.frogs.length,3);pass('disconnected healthy frog remains infectable and reconnect restores same identity/current infection and score');await Promise.all(group.map(p=>p.leave()));
 writeFileSync('docs/results/outbreak.json',JSON.stringify({environment:'Independent loopback WebSocket clients using actual OutbreakRoom/Planck contacts; test-only arrangements and shortened announcement/countdown (6/12 ticks), production grace remains 60 ticks; not human acceptance',checks,matches},null,2));
}finally{await Promise.allSettled(peers.map(p=>p.leave()));server.kill();}
