const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium');const {spawn}=require('node:child_process'),fs=require('node:fs');
(async()=>{binary.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:'3077',ENABLE_TESTS:'1'}});let log='';server.stdout.on('data',x=>log+=x);server.stderr.on('data',x=>log+=x);let browser;
try{
 await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(log.includes('listening')){clearInterval(timer);resolve();}},50);setTimeout(()=>{clearInterval(timer);reject(Error(log));},10000);});
 browser=await chromium.launch({executablePath:await binary.executablePath(),headless:true,args:[...binary.args,'--no-sandbox','--disable-dev-shm-usage']});const pages=[],errors=[],checks=[];
 for(let i=0;i<3;i++){const context=await browser.newContext({viewport:{width:1280,height:1000}}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));pages.push(p);await p.goto('http://127.0.0.1:3077/');await p.locator('#name').fill(`Browser Frog ${i+1}`);if(i===0){await p.locator('#create').click();await p.waitForFunction(()=>document.querySelector('#code').textContent.length===6);}else{await p.locator('#join-code').fill(await pages[0].locator('#code').textContent());await p.locator('#join').click();await p.locator('#lobby').waitFor({state:'visible'});}}
 const host=pages[0];for(const p of pages)await p.locator('#ready').click();await host.locator('#start').click();await host.waitForFunction(()=>window.spikeDebug.outbreak?.phase==='announcement');const order=await host.evaluate(()=>window.spikeDebug.outbreak.patientZeroOrder);if(new Set(order).size!==3)throw Error('invalid rotation');
 const initial=await host.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs.map(f=>f.x));await host.keyboard.down('KeyD');await host.keyboard.down('Space');await host.waitForTimeout(300);await host.keyboard.up('Space');await host.keyboard.up('KeyD');const locked=await host.evaluate(()=>window.spikeDebug.snapshots.at(-1).state.frogs.map(f=>f.x));if(JSON.stringify(initial)!==JSON.stringify(locked))throw Error('countdown controls moved frogs');checks.push('Patient Zero announcement visible; countdown input locked');
 const started=Date.now(),rounds=[];
 async function arrange(positions){const before=await host.evaluate(()=>window.spikeDebug.lastReset);await host.evaluate(p=>window.spikeDebug.room.send('outbreak-test',{positions:p}),positions);await host.waitForFunction(previous=>window.spikeDebug.lastReset!==previous,before);}
 for(let round=1;round<=3;round++){
  await host.waitForFunction(r=>window.spikeDebug.outbreak?.phase==='playing'&&window.spikeDebug.outbreak.round===r,round);await Promise.all(pages.map(p=>p.waitForFunction(()=>window.spikeDebug.playing)));const zero=await host.evaluate(()=>window.spikeDebug.outbreak.patientZero),targets=[0,1,2].filter(i=>i!==zero);const box=await host.locator('canvas').boundingBox();if(!box||box.width<300||box.height<200)throw Error('arena missing on round transition');
  if(round===1){const positions=[[3,16],[16,9],[29,16]];positions[zero]=[16,9];positions[targets[0]]=[16.88,9];positions[targets[1]]=[3,16];await arrange(positions);await host.waitForFunction(slot=>window.spikeDebug.outbreak.players[slot].state==='transforming',targets[0]);const affected=pages[targets[0]];await affected.locator('#infection-feedback').filter({hasText:'survival'}).waitFor({state:'visible'});await host.screenshot({path:'docs/results/outbreak-5-1-grace.png'});checks.push('infection feedback and distinct healthy/Patient Zero/grace states displayed');
   const gracePositions=[[3,16],[16,21.05],[29,16]];gracePositions[zero]=[3,16];gracePositions[targets[0]]=[16,21.05];gracePositions[targets[1]]=[16.88,21.05];await arrange(gracePositions);await host.waitForTimeout(200);const healthy=await host.evaluate(slot=>window.spikeDebug.outbreak.players[slot].state==='healthy',targets[1]);if(!healthy)throw Error('grace allowed an immediate infection chain');await host.waitForFunction(()=>window.spikeDebug.outbreak.phase==='round-results');
  }else{const positions=[[16,9],[15.12,9],[16.88,9]];positions[zero]=[16,9];positions[targets[0]]=[15.12,9];positions[targets[1]]=[16.88,9];await arrange(positions);await host.waitForFunction(()=>window.spikeDebug.outbreak.phase==='round-results');await host.locator('#results').waitFor({state:'visible'});await host.locator('#standings').filter({hasText:'(tied)'}).waitFor({state:'visible'});const rows=await host.locator('#standings').textContent();if(!rows.includes('(tied)'))throw Error('simultaneous infection ties not shown');}
  await Promise.all(pages.map(p=>p.locator('#results').waitFor({state:'visible'})));const record=await host.evaluate(()=>window.spikeDebug.outbreak);if(record.patientZero!==order[round-1])throw Error('Patient Zero order changed');rounds.push({round,patientZero:zero,points:record.players.map(p=>p.roundPoints),winners:record.roundWinners,elapsedMs:record.elapsedMs});const stopped=record.elapsedMs;await host.waitForTimeout(100);if(await host.evaluate(()=>window.spikeDebug.outbreak.elapsedMs)!==stopped)throw Error('results timer kept running');await host.locator('#next-round').click();
 }
 await host.locator('#results-title').filter({hasText:'MATCH COMPLETE'}).waitFor({state:'visible'});const totals=await host.evaluate(()=>window.spikeDebug.outbreak.players.map(p=>p.totalPoints));const expected=[0,0,0];for(const r of rounds)r.points.forEach((v,i)=>expected[i]=Math.round(expected[i]*10+v*10)/10);if(JSON.stringify(totals)!==JSON.stringify(expected))throw Error('incorrect survival totals');await host.screenshot({path:'docs/results/outbreak-5-1-final.png'});checks.push('three rounds, Patient Zero rotation, tied infection rows, final totals/placements and stopped timer');await host.locator('#return-lobby').click();await Promise.all(pages.map(p=>p.locator('#lobby').waitFor({state:'visible'})));await pages[2].locator('#leave').click();await host.waitForFunction(()=>window.spikeDebug.lobby.players.length===2);
 // A real two-player rematch with deliberately different survival times should produce a unique winner.
 for(const p of pages.slice(0,2))await p.locator('#ready').click();const rematchStarted=Date.now();await host.locator('#start').click();await host.waitForFunction(()=>window.spikeDebug.outbreak?.phase==='announcement');for(let round=1;round<=2;round++){await host.waitForFunction(r=>window.spikeDebug.outbreak.phase==='playing'&&window.spikeDebug.outbreak.round===r,round);if(round===1&&Date.now()-rematchStarted<3800)throw Error('rematch skipped production countdown');if(round===2)await host.waitForTimeout(1500);await arrange([[16,9],[16.88,9]]);await host.locator('#results').waitFor({state:'visible'});await host.locator('#next-round').click();}
 await host.locator('#results-title').filter({hasText:'MATCH COMPLETE'}).waitFor({state:'visible'});if((await host.locator('#winner-message').textContent()).includes('Shared winners'))throw Error('unequal survival durations should differ');checks.push('return-to-lobby rematch resets roster/scores; two-player distinct survival scores and unique victory');await host.locator('#return-lobby').click();await host.locator('#lobby').waitFor({state:'visible'});for(const p of pages.slice(0,2))await p.locator('#leave').click();
 if(errors.length)throw Error(JSON.stringify(errors));const report={environment:'Three isolated local headless Chromium contexts, production announcement/countdown/grace timing, test-only body arrangement; not human acceptance',checks,rounds,totals,durationSeconds:(Date.now()-started)/1000,errors};fs.writeFileSync('docs/results/outbreak-browser-5-1.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
