// Original presentation QA on an isolated local server/browser; no public test hooks.
const {chromium}=require('playwright-core'),bin=require('@sparticuz/chromium'),{spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{bin.setGraphicsMode=false;const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,PORT:'3199',HOST:'127.0.0.1',ENABLE_TESTS:'1'}});let log='',browser;server.stdout.on('data',b=>log+=b);server.stderr.on('data',b=>log+=b);const errors=[],checks=[];
try{await new Promise((r,j)=>{const timer=setInterval(()=>{if(log.includes('listening')){clearInterval(timer);r();}},25);setTimeout(()=>{clearInterval(timer);j(Error(log));},10000);});browser=await chromium.launch({executablePath:await bin.executablePath(),args:[...bin.args,'--no-sandbox','--disable-dev-shm-usage'],headless:true});const pages=[];
for(let i=0;i<8;i++){const context=await browser.newContext(i===7?{hasTouch:true,isMobile:true,viewport:{width:844,height:390}}:{viewport:{width:1440,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));pages.push(page);await page.goto('http://127.0.0.1:3199');if(i===0){await page.screenshot({path:'docs/results/m6-home.png'});await page.locator('#name').fill('Sprout');await page.locator('#create').click();await page.waitForFunction(()=>document.querySelector('#code').textContent.length===6);}else{await page.locator('#name').fill(['Sprout','Mango','Puddle','Petal','Plum','Dandelion','Mint','Orchid'][i]);await page.locator('#join-code').fill(await pages[0].locator('#code').textContent());await page.locator('#join').click();await page.locator('#lobby').waitFor({state:'visible'});}}
const host=pages[0],phone=pages[7];await host.screenshot({path:'docs/results/m6-lobby.png'});assert.equal(await host.locator('.player-card').count(),8);for(const page of pages)await page.locator('#ready').click();await host.locator('#sound').click();assert.equal(await host.locator('#sound').getAttribute('aria-pressed'),'true');await host.locator('#start').click();await host.locator('#phase-overlay').waitFor({state:'visible'});await host.screenshot({path:'docs/results/m6-reveal.png'});await host.waitForFunction(()=>window.spikeDebug.outbreak?.phase==='countdown');await host.screenshot({path:'docs/results/m6-countdown.png'});await host.waitForFunction(()=>window.spikeDebug.playing);await host.locator('#phase-overlay').waitFor({state:'hidden'});checks.push('eight identities; lobby, Patient Zero and countdown visual states; opt-in procedural audio; intro overlay removed for gameplay');
async function arrange(positions){const reset=await host.evaluate(()=>window.spikeDebug.lastReset);await host.evaluate(p=>window.spikeDebug.room.send('outbreak-test',{positions:p}),positions);await host.waitForFunction(old=>window.spikeDebug.lastReset!==old,reset);await host.waitForTimeout(120);}
await arrange([[7,15.3],[12,10.8],[20,6.3],[28,10.8],[33,15.3],[7,4.3],[33,4.3],[20,21.05]]);await host.screenshot({path:'docs/results/m6-arena-desktop.png'});await phone.screenshot({path:'docs/results/m6-arena-phone.png'});const canvas=await phone.locator('canvas').boundingBox(),pad=await phone.locator('#direction-pad').boundingBox(),action=await phone.locator('#touch-action').boundingBox();assert.ok(canvas.x>=pad.x+pad.width&&canvas.x+canvas.width<=action.x);assert.ok(canvas.y+canvas.height<=390);checks.push('eight-player arena and phone screenshot; controls disjoint, arena inside viewport');
const frameMs=await host.evaluate(()=>new Promise(resolve=>{let last=performance.now(),samples=[];function next(t){samples.push(t-last);last=t;if(samples.length===120)resolve(samples.slice(1));else requestAnimationFrame(next);}requestAnimationFrame(next);}));frameMs.sort((a,b)=>a-b);const frames={median:frameMs[Math.floor(frameMs.length*.5)],p95:frameMs[Math.floor(frameMs.length*.95)],max:frameMs.at(-1),note:'Eight concurrent headless browser contexts on shared runner; diagnostic only, not physical-device FPS'};
const zero=await host.evaluate(()=>window.spikeDebug.outbreak.patientZero),target=(zero+1)%8,pos=Array.from({length:8},(_,i)=>[2+36*i/7,21.05]);pos[zero]=[18,21.05];pos[target]=[18.88,21.05];await arrange(pos);await host.waitForFunction(slot=>window.spikeDebug.outbreak.players[slot].state==='transforming',target);await host.screenshot({path:'docs/results/m6-infection-grace.png'});await host.waitForFunction(slot=>window.spikeDebug.outbreak.players[slot].state==='infectious',target);await host.screenshot({path:'docs/results/m6-infection-poison.png'});checks.push('real body contact: grace and poison visuals; names, state words, crown, X cheeks and spores supplement colors');
await phone.goto('about:blank');await host.waitForFunction(()=>window.spikeDebug.lobby.players[7].connected===false);await host.screenshot({path:'docs/results/m6-offline.png'});checks.push('offline frog stays in world with OFFLINE label');await host.locator('#sound').click();assert.equal(await host.locator('#sound').getAttribute('aria-pressed'),'false');assert.deepEqual(errors,[]);fs.writeFileSync('docs/results/presentation-milestone-6.json',JSON.stringify({environment:'Local compiled production server and eight Chromium clients, one emulated touch phone. No physical-device acceptance claim.',checks,frames,phoneLayout:{canvas,pad,action},errors},null,2));console.log(JSON.stringify({checks,frames,errors}));
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
