import {spawn} from 'node:child_process';import {writeFileSync,mkdirSync} from 'node:fs';
import {Client,type Room} from 'colyseus.js';import type {Snapshot,LobbyState} from '../src/network/protocol';import type {OutbreakView} from '../src/game/outbreak';import {summary} from '../server/metrics';
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
// Exercise the same compiled entrypoint as Render, not the development TypeScript loader.
const server=spawn(process.execPath,['server-dist/index.js'],{env:{...process.env,HOST:'127.0.0.1',PORT:'2767'},stdio:['ignore','pipe','pipe']});server.stderr.on('data',x=>process.stderr.write(x));
const rooms:Room[]=[],intervals:ReturnType<typeof setInterval>[]=[],durations:number[]=[];let last:Snapshot|undefined;let messages=0,bytes=0,attached=0,lastTick=0,lastAt=0,start=0,clockTicks=0,playingTicks=0,rounds=0,matches=0;let running=false,phase='',lastContinuation='';
try{
 let ready='';await new Promise<void>((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server timeout')),10000);server.stdout.on('data',x=>{ready+=x;if(ready.includes('listening')){clearTimeout(t);resolve();}});server.once('exit',x=>reject(Error(`server exit ${x}`)));});
 const c=new Client('ws://127.0.0.1:2767');for(let i=0;i<8;i++){const r=i?await c.joinById(rooms[0].roomId,{name:`Bot ${i+1}`}):await c.create('frog_party',{name:'Bot 1'});rooms.push(r);
  r.onMessage('lobby',(state:LobbyState)=>{if(!running||state.phase!=='lobby')return;const me=state.players.find(p=>p.id===r.sessionId);if(me&&!me.ready)r.send('ready',true);if(i===0&&state.players.length===8&&state.players.every(p=>p.ready))r.send('start');});
  r.onMessage('outbreak',(state:OutbreakView|null)=>{if(i!==0||!state)return;phase=state.phase;const key=`${matches}:${state.round}:${phase}`;if(key===lastContinuation)return;if(phase==='round-results'){lastContinuation=key;rounds++;r.send('next-round');}else if(phase==='match-results'){lastContinuation=key;matches++;r.send('return-lobby');}});
  r.onMessage('notice',()=>{});r.onMessage('welcome',()=>{});r.onMessage('pong',()=>{});
  r.onMessage('snapshot',(s:Snapshot)=>{messages++;bytes+=JSON.stringify(s).length;if(i===0){last=s;attached+=s.state.frogs.filter(f=>f.tongue?.phase==='attached').length;const delta=s.state.tick>=lastTick?s.state.tick-lastTick:s.state.tick;clockTicks+=delta;if(phase==='playing')playingTicks+=delta;if(lastAt)durations.push(Date.now()-lastAt);lastAt=Date.now();lastTick=s.state.tick;}});r.send('hello');
  let seq=0,n=0;intervals.push(setInterval(()=>{n++;const p=n%150,x=i%2?-1:1;r.send('input',{seq:++seq,at:Date.now(),input:{x:n%240<120?x:-x,y:p>=38&&p<115?-1:0,held:p<28||p>=38&&p<115}});},1000/30));
 }
 if(process.env.ARENA_TEST_ID)rooms[0].send('select-arena',process.env.ARENA_TEST_ID);
 running=true;for(const r of rooms)r.send('ready',true);start=Date.now();await wait(Number(process.env.STRESS_SECONDS??60)*1000);const elapsed=Date.now()-start;
 if(!last||last.state.frogs.length!==8||playingTicks<500||(!process.env.ARENA_TEST_ID&&rounds<1))throw Error('insufficient eight-player active Outbreak load');
 const result={arenaId:last.arenaId,environment:'One local production OutbreakRoom, eight real loopback WebSocket clients at 30 inputs/client/sec, bots jumping/grappling/colliding; host advances results and rematches; production countdown/grace timing; not a production-host capacity claim',seconds:elapsed/1000,clients:8,physicsBodies:last.state.frogs.length,authoritativeClockTicks:clockTicks,activeGameplayTicks:playingTicks,completedRounds:rounds,completedMatches:matches,tickMs:last.tickMs,overruns:last.overruns,receivedSnapshotMessages:messages,snapshotGapMs:summary(durations),payloadBytesReceivedAllClients:bytes,attachedObservations:attached};
 mkdirSync('docs/results',{recursive:true});writeFileSync(process.env.ARENA_TEST_ID?`docs/results/stress-${process.env.ARENA_TEST_ID}-milestone-8.json`:'docs/results/stress-milestone-6.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(last.overruns>0||last.tickMs.p99>8)throw Error('tick budget acceptance failed');
}finally{for(const i of intervals)clearInterval(i);for(const r of rooms)await r.leave();server.kill();}
